### ISSUE TITLE
Preserve default influxDB ordering

### ISSUE THREAD

**Issue by behrad** [node-influx/node-influx#105]
InfluxDB orders results descending, (as in queryRaw) however when parsingResults in `query` `.sort` changes default ordering to Ascending.
I propose disabling `.sort` by default, and/or defining a new query option for caller to set the ordering

**Comment by behrad** [comment]
just saw https://github.com/node-influx/node-influx/commit/3ad80e5e05c3fa5df93589c6b07f6058a3a4ac8f
Nice, thank you :)

**Comment by behrad** [comment]
https://github.com/node-influx/node-influx/issues/99#issuecomment-147469741

**Comment by bencevans** [comment]
Fixed by https://github.com/node-influx/node-influx/commit/3ad80e5e05c3fa5df93589c6b07f6058a3a4ac8f
