### ISSUE TITLE
How to update tags of existing data points

### ISSUE THREAD

**Issue by raimohanska** [node-influx/node-influx#109]
I've been trying to update some existing data points using this API. The problem is that I always end up inserting new ones instead, probably because I'm unable to pass the timestamp correctly. What I'm doing is essentially

```js
    var query="..."
    client.query(query, (err, data) ->
      data[0].forEach((event) ->
        client.writePoint(seriesName, { value: event.value, time: new Date(event.time) }, { testtag1: "boom" })
      )
    )
```

I also tried to pass the `time` from the query result event to `writePoint` but it doesn't seem to work either: I get `unable to parse 'temperature,testtag3=boom value=12.7 2015-10-15T19:51:51.140565896Z': bad timestamp`

Any idea how to make this work? Maybe writePoint should also accept the string value that I get from the query?

**Comment by bencevans** [comment]
You may need to send raw queries to acheive this. I'm not sure if Influx
supports UPDATE queries (can't find anything from a quick search) but
haven't needed to personally. Otherwise you are able to delete points (
http://stackoverflow.com/a/26283092) then write the new values in.
