### ISSUE TITLE
Support "Other options when querying data"

### ISSUE THREAD

**Issue by bencevans** [node-influx/node-influx#112]
Add support to specify [other options when querying data](https://influxdb.com/docs/v0.9/guides/querying_data.html#other-options-when-querying-data). Add an options object to `query`/`rawQuery` functions which urlencodes the data and append to request's querystring.

Suggested API...

```
client.query([database], query, [options], callback)
```
```
 database - Optional String
 query - String
 options - Object - declaire timestampFormat/chunkSize
           .timestampFormat = String (`epoch=[h,m,s,ms,u,ns]`)
           .chunkSize = Integer (`epoch=[h,m,s,ms,u,ns]`)
           .raw - Object
                 .* - adds to querystring
```
  
**associated issues** 

* #39 Handle chunked query responses (epoch)
  > curl -G 'http://localhost:8086/query' --data-urlencode "db=mydb" --data-urlencode "epoch=s" --data-urlencode "q=SELECT value FROM cpu_load_short WHERE region='us-west'"

* #111 Query different timestamp formats (chunk_size)

  > curl -G 'http://localhost:8086/query' --data-urlencode "db=deluge" --data-urlencode "chunk_size=20000" --data-urlencode "q=SELECT * FROM liters"

**docs**

* [curl man page](http://linux.die.net/man/1/curl)

* https://influxdb.com/docs/v0.9/guides/querying_data.html#other-options-when-querying-data

**Comment by connor4312** [comment]
As of 5.x, all documented Influx options are available in the query methods.
