### ISSUE TITLE
Include series name in multi-series query

### ISSUE THREAD

**Issue by kevinthorley** [node-influx/node-influx#113]
For queries that span multiple series, I would like the results to include the series name. I'm not sure if there is a way to do this that exists today. Based on reading over _parseResults, this doesn't seem to be the case. I am able to easily modify _parseResults to achieve this result and would be happy to submit a PR if this is a reasonable request.

I am executing a query similar to the following:
SELECT LAST(value) FROM /.*/ WHERE sensorGroupId = 'some_id' GROUP BY sensorId

The results that are returned via node-influx are formatted as follows:
```
[ [ { time: '1970-01-01T00:00:00Z',
      last: 16,
      sensorId: 'a485a016-de0d-48bf-94ef-26063236f12a' },
    { time: '1970-01-01T00:00:00Z',
      last: 6,
      sensorId: 'e445de61-0238-484d-8a1f-5e3b88fc9d2b' },
....
```

As you can see, there is no series name returned as part of the results. 

The results returned from the influxdb command line are as follows:
```
> SELECT LAST(value) FROM /.*/ WHERE sensorGroupId='some_id' group by sensorId
name: sensor.typeA.subtypeA
tags: sensorId=123abc
time			last
----			----
1970-01-01T00:00:00Z	47

name: sensor.typeA.subtypeB
tags: sensorId=456def
time			last
----			----
1970-01-01T00:00:00Z	46
............
```

I would like to see the following returned from influx-node:
The results that are returned via node-influx are formatted as follows:
```
[ [ { time: '1970-01-01T00:00:00Z',
      last: 16,
      sensorId: '123abc',
      name: 'sensor.typeA.subtypeA' },
    { time: '1970-01-01T00:00:00Z',
      last: 6,
      sensorId: '456def',
      name: 'sensor.typeA.subtypeA' },
.................
```

**Comment by kevinthorley** [comment]
Just realized I can accomplish what I need with queryRaw. What was the original intent behind exposing the raw query results vs the parsed results?

**Comment by leorossi** [comment]
I have a similar issue with a multi-series query.
I find that the results given back by influxdb, that is before `_parseResults` are well formatted. 
Maybe add an option `parseResults: true|false` can be an easire solution for the ones who need the raw influxdb data?

**Comment by bencevans** [comment]
Happily accept a pull-request. Ta, Ben.

**Comment by connor4312** [comment]
Resolved in https://github.com/node-influx/node-influx/commit/d5fc075192729f83b3368a75c9ea5e615e819a05, releasing tomorrow.
