### ISSUE TITLE
Error: 404 page not found in `err`

### ISSUE THREAD

**Issue by robcalcroft** [node-influx/node-influx#114]
```javascript
var client = require("influx")({
    host : 'localhost',
    username : 'root',
    password : 'root',
    database : 'test',
    port: 8086
});

client.writePoint("availability", [
    {
        time: new Date(),
        value: "1"
    },
    {
        time: new Date(),
        value: "2"
    }
], function(err, result) {
    console.log(err, result);
});
```
Gives `[Error: 404 page not found] undefined` on the command line

Using `8088` gives a socket hangup error.

**Comment by gavinmcnair** [comment]
I've got this too!

**Comment by CrazyIvan007** [comment]
When installed with npm, check version of your node-influx. If you have 3.5 and Influxdb 0.9 then you have to install node-influx version 4.0, because node-influx 3.x is for Influxdb 0.8 and between this two versions there where changes to the endpoints.

**Comment by gavinmcnair** [comment]
Thanks.

That coupled with moving the database name into the writePoint options seems to have fixed the issues. Now just to get the data looking good :)

**Comment by robcalcroft** [comment]
That worked!! :) thanks

**Comment by dougestey** [comment]
FYI, installing from npm gives version 3.5.0 by default. I was hung up on this for about an hour before finding this issue.
