### ISSUE TITLE
Retrieve written data when written in tests to ensure Influx has stored it.

### ISSUE THREAD

**Issue by SamuelToh** [node-influx/node-influx#115]
Hi guys,

I was just browsing through the test.js file and realize that some of the "write-to-db" tests can potentially give us false results because the code only ensures that data are written to DB with no error but it did not check whether the contents are indeed written.

Take for example:

````
describe('#writePoints', function () {
    this.timeout(10000)
    it('should write multiple points to the same time series, same column names', function (done) {
      var points = [
        [{value: 232}, { foobar: 'baz'}],
        [{value: 212}, { foobar: 'baz'}],
        [{value: 452}, { foobar: 'baz'}],
        [{value: 122}]
      ]
      dbClient.writePoints(info.series.name, points, done)
    })
````

I suppose there should be 4 rows written to influx but it seems like only the last 2 rows are getting written. I think in such scenario the test should be flagged as failure but it is currently reporting as passed.

Do you guys think we should improve on the tests to confirm that data are written?

Cheers,
Sam

**Comment by SamuelToh** [comment]
And I think, can't confirm, the reason why only 2 out of the 4 rows were written to influx was due to we not specifying the time attribute 

Since we did not give each row a unique time stamp, influx will try to workout a time for them, i think the time is just the current time when it is processing the rows. So let say 2 rows are getting processed at an approximate time(same time) then influx will only pick 1 for insertion insert, due to time clashing.

If I modifying the test take in a unique time attribute then we can see 4 rows getting inserted everytime.

````
describe('#writePoints', function () {
    this.timeout(10000)
    it('should write multiple points to the same time series, same column names', function (done) {
      var points = [
        [{value: 1009, time: 1234567890 }, { foobar: 'bazxxx'}],
        [{value: 1111, time: 1234667890 }, { foobar: 'bazxxx'}],
        [{value: 1222, time: 1234767890 }, { foobar: 'bazxxx'}],
        [{value: 1333, time: 1234867890 }, { foobar: 'tetexxx'}]
      ]
      console.log("The series name => " + info.series.name);
      dbClient.writePoints(info.series.name, points, done)
    })
````

**Comment by bencevans** [comment]
Wow, thanks for the review! Yes any improvements would be ace!!!

**Comment by connor4312** [comment]
No longer relevant, see https://github.com/node-influx/node-influx/issues/192
