### ISSUE TITLE
Records not inserted if precision is not nanoseconds

### ISSUE THREAD

**Issue by mauvm** [node-influx/node-influx#116]
I'm using InfluxDB v0.9.5 and if the precision is not `ns` (nanoseconds), the records are not inserted. No error/warning whatsoever. Also see https://goo.gl/3NcNwM:

> The ability to query with different precisions was unhooked in the transition from 0.8.8 to 0.9.0. It will return, but meanwhile the workaround is to always specify timestamps in nanosecond precision as per RFC 3339.

Anyone else experiencing this issue? Should the default precision be changed to `ns`?

**Comment by esatterwhite** [comment]
Not sure if this is completely related, If I try to set the timestamp property, to anything really, with the `write` function, the date is always `1970-01-01T00:24:10.446448273Z`

If I omit the time stamp property, the date is accurate.

**Comment by bencevans** [comment]
Hi @mauvm 

Did you ever find the solution or issue behind this? If you'd be able to write a test covering your case we can be sure it's fixed properly and don't break it in the future.

Cheers

Ben

**Comment by mauvm** [comment]
My solution was to multiply the timestamp to nanoseconds. A test won't be necessary, since we're already at v0.13 (which always uses nanoseconds). As said in the Google Groups: the feature will return. So I'll update to a newer version and wait it out.

Thanks for your help!

**Comment by bencevans** [comment]
Thanks for updating @mauvm
