### ISSUE TITLE
Influx on HTTPS Tests

### ISSUE THREAD

**Issue by bencevans** [node-influx/node-influx#117]

**Comment by sinozhou** [comment]
Hi,
I found the error when try to connect the ssl enabled influxdb 0.11 with self signed cert
Cannot write data [Error: {"error":"unable to parse 'response_times value=undefined': invalid boolean"}
]

Regards,

**Comment by sinozhou** [comment]
Hi,
Sorry, my test app has some bug. For ssl it worked.
But for self signed cert, should set envirment value export NODE_TLS_REJECT_UNAUTHORIZED=0
Regards

**Comment by dandv** [comment]
@sinozhou: do you really need a self-signed cert? LetsEncrypt offers super easily certificates recognized by all browsers.

**Comment by connor4312** [comment]
Closing this. We have functional tests that test over normal HTTP, I don't think adding tests specifically for HTTPS beyond the configuration/constructing tests in the pool and InfluxDB constructor is valuable.

**Comment by dandv** [comment]
I'd agree. Any errors we uncover will pertain to the underlying library, or to InfluxDB.

Sadly for the project, I've also switched from HTTPS to an SSH tunnel and setting the host to localhost, which gives my app portability to be run without config changes from any machine, from my laptop to the InfluxDB host itself.

### package.json

```json
...
"scripts": {
  "ssh": "ssh -fnNT -L 8086:localhost:XXXX dandv@example.com -p YYYY -i /path/to/my/private.key",
}
...
```

Where XXXX and YYYY are random ports other than 8086 and 22, respectively (a security-through-obscurity practice that's very cheap to implement and thwarts a the majority of botnet attacks).

**Comment by connor4312** [comment]
Probably for the better, we will of course support SSL and password auth, but (from my view) sysadmins should try their hardest to makes them unnecessary. A network or tunnel physically segregated or firewalls from the rest of the world is always going to be more secure than any password auth, much less the implementation of that authentication...
