### ISSUE TITLE
InfluxDB 1.0 support

### ISSUE THREAD

**Issue by janantala** [node-influx/node-influx#122]
Is this library compatible with InfluxDB 0.10.x?

**Comment by eliperelman** [comment]
@janantala it's still not fully compatible with InfluxDB 0.9.3, so I would say no.

**Comment by eliperelman** [comment]
I mean, I'm sure some core things should still work, but there will still be things that are broken.

**Comment by bencevans** [comment]
There's currently a few issues running the test suit on 0.10.0...
https://travis-ci.org/node-influx/node-influx/jobs/108624409 I won't be
fixing for 0.10 any-time soon but a pull-request is always welcome :)

**Comment by niieani** [comment]
0.11 is already out. Did anybody test node-influx on it yet?

**Comment by thinkdevcode** [comment]
I'm currently working on updating this lib for v0.12 compatibility in my fork. There are some major breaking changes between this version and my fork, so i'm not sure if a PR would be welcome? I tried to avoid compatibility issues but unfortunately influxdb has changed substantially over the last 6 months.

**Comment by bencevans** [comment]
That's absolutely fine. It was pretty inevitable breaking changes would
happen as this client was written in the early days of InfluxDB.

We can publish a changelog and release the updated version as new major
release in accordance to semantic versioning.

I'm unable to contribute any time to this project at the moment but would
love to see the project move forward. If you're interested in maintaining
please get in touch!

All the best,

Ben

**Comment by niieani** [comment]
@thinkdevcode I looked at your fork - great progress! Would you say your 0.12 is production-ready?

**Comment by thinkdevcode** [comment]
@niieani not yet, I will be testing the lib on a production system in the following couple weeks. For development you could probably start using it now.

**Comment by Apollon77** [comment]
... and we have InfluxDB 1.0 now :-)

**Comment by niieani** [comment]
indeed, for some time now. Are there many breaking changes since 0.12?

**Comment by Apollon77** [comment]
https://docs.influxdata.com/influxdb/v0.13/administration/012_vs_013/
and
https://docs.influxdata.com/influxdb/v1.0/administration/013_vs_1/
should be relevant ...
There are some changes to "query" and "group by time" and such.

Breaking may only be:
`The keywords IF, EXISTS, and NOT where removed for this release. This means you no longer can or need to specify IF EXISTS for DROP DATABASE or IF NOT EXISTS for CREATE DATABASE. If these are specified, a query parse error is returned.`

... but maybe more ...

**Comment by connor4312** [comment]
Updating this to target support for Influx 1.0 in 5.0.0. Happy to have a fully stable platform to work against :)

**Comment by connor4312** [comment]
Version 4.x tests pass in Influx 1.0, 5.x brings "native" support for 1.0 with no guarantees of support for versions prior to that.

**Comment by connor4312** [comment]
These changes have been published in `5.0.0-alpha.1`. You can install this via:

```
npm install --save influx@next
```

**Comment by niieani** [comment]
Lovely, thanks for your hard work!
