### ISSUE TITLE
Uncaught TypeError: client.query is not a function

### ISSUE THREAD

**Issue by carlobailey** [node-influx/node-influx#124]
Please excuse the amateur question - but I am new to node/javascript. 

I am trying to do an influxdb request in my browser on a local server. But for the life of me I cannot figure out where I am going wrong. I keep getting a TypeError in my code and another TypeError 'depMaps.slice is not a function' within the 'Require.js' file. Here is my code:

`var influx = require(['influx'], function (influx) {})
            
            var host =  'hostname'
            var port = 8086 
            var username = 'user'
            var password = 'password'
            var database = 'test'
            var client = influx({host,port,username,password,database})
            var query = "select * from dbase where time > '2016-03-08T16:30:00.14Z'"
            client.query(query, function(err){
                if (err) throw err
                console.log('Success')
            });`

Any help much appreciated. Thanks!

**Comment by bencevans** [comment]
Hi @carlobailey 

I believe this is due to the way you're requiring the module. The `require` function is synchronous and doesn't quite fit the syntax you're using.

When requiring the module try the following:

```js
var influx = require('influx')

// Then whatever you wish to do with the module...
var client = influx(opts)
client.query(query), function (err, res) {

})
```
