### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by jamesbaber** [node-influx/node-influx#125]
I'm struggling to get writePoints working and would appreciate some more /examples that I and other users can use to get started

**Comment by bencevans** [comment]
Please could you leave details as to what issue your hitting so we can make sure the examples cover such scenario.

https://github.com/node-influx/node-influx/blob/master/examples/express_response_times/app.js provides an example using writePoints.

**Comment by dandv** [comment]
Hey @jamesbaber, here's a [working example for batching `writePoint`s](https://github.com/node-influx/node-influx/issues/178).
