### ISSUE TITLE
General ideas going forwards

### ISSUE THREAD

**Issue by connor4312** [node-influx/node-influx#138]
I thought I'd put up some of my thoughts on the state of the driver and what we could do going forward:

**Tests**: important, because these will be what we use to ensure things don't all break:
- first, update the tests to Influx 0.12 (6 are currently failing) and also make tests be more stateless. Right now test only run in order and depend on state created in previous tests. This removes the ability to run specific tests and makes failures more difficult to diagnose
- also, use sinon to mock time in tests. Makes it run faster and is less flaky

**Structure**:
- Currently everything is shoved in the main Influx class. It'd be very nice to split things out and test them as individual modules (a dedicated pool module, a protocol module, etc.). Allows for better test [boundaries](https://www.destroyallsoftware.com/talks/boundaries) and more focused, precise tests.
- This would also let us test performance of particular modules--I admit to being a bit of a performance enthusiast--and tuning it would be quite beneficial to high-throughput apps. As of 0.10 Influx noted it could handle many [hundreds of thousands of writes](https://influxdata.com/blog/announcing-influxdb-v0-10-100000s-writes-per-second-better-compression/) per second; node-influx should not bottleneck that!

**General:**
- It seems that there are still some cases where things are encoded incorrectly when writing. While splitting it out, I'd like to try to do a direct translation of their official [Go client](https://godoc.org/github.com/influxdata/influxdb/client/v2) and also stick a fuzzer at it to flush out any remaining issues
- Finally get HTTPS tests working? 😄 
- Long term: UDP protocol support would be neat, but that's basically its entirely own thing. I wrote a good chunk of a Go Influx client (their official client has a very poor API) and trying to 'unify' the HTTP and UDP protocols into a single seamless API seemed like more trouble than it was worth.

**Comment by SPARTAN563** [comment]
Sounds good to me. I'm happy to help out if you guys need (or would like) a hand.

On the topic of UDP, if that's something you'd like to add then maybe it's a good idea to build (as part of breaking everything into its own module) a pluggable transport/encoding layer. One  thing to keep in mind though is that some of the API methods aren't available over UDP - it's essentially just a data intake protocol - so it may make more sense to just do the transports work for data intake protocols (HTTP+LineProtocol and UDP).

Another thing to keep in mind where the Go client is concerned, is that Golang has type information available for things like converting to integers (`123i`) - that sort of behaviour is a bit more tricky in JS.

**Comment by taybin** [comment]
Any updates on these ideas?  I'd love to see UDP support.

**Comment by bencevans** [comment]
UDP support would be cool. PR welcome
