### ISSUE TITLE
Calling writePoints without options results in error

### ISSUE THREAD

**Issue by foxx** [node-influx/node-influx#143]
As seen here;

```
error:   TypeError: Cannot read property 'database' of undefined
    at InfluxDB.writeSeries (/opt/code/node_modules/influx/index.js:339:15)
    at InfluxDB.writePoints (/opt/code/node_modules/influx/index.js:371:8)
```

This is because although `options` is an optional field, there is no default being set, thus it results in an undefined. Can probably be fixed with a quick null check. Thoughts?

**Comment by SPARTAN563** [comment]
Hi there @foxx, which version of the package are you using at the moment? Our latest code shouldn't encounter this issue (just did a quick manual run-through to check).

**Comment by foxx** [comment]
Currently using `4.2.0`, the latest on npm.

Just tried on master, but this time got an entirely new bug;

```
npm install https://github.com/node-influx/node-influx/tarball/master
/opt/code/node_modules/influx/index.js:102
      return callback(new Error(body.error || body))
             ^

TypeError: callback is not a function
    at /opt/code/node_modules/influx/index.js:102:14
```

Guessing it's the same problem but for `callback` this time?

**Comment by SPARTAN563** [comment]
Ah, thanks for bringing that up - seems it's something the tests didn't catch, the `callback` wasn't being passed around correctly for the `writePoints` function.

I've just opened a pull request with the fix, our contributor agreement requires someone to review it, but in the mean time you can use `npm install node-influx/node-influx#fix-write-points-callback` to install that version for testing.

**Comment by SPARTAN563** [comment]
PR for reference: #144

**Comment by foxx** [comment]
Beautiful, thanks for the quick turn around, keep up the fantastic work :)

**Comment by foxx** [comment]
Just tested master@45cf4b7c, all worked fine!

PS) the `npm install` command you pasted didn't work, had to use the tarball one
