### ISSUE TITLE
Deprecated use of GET for POST commands

### ISSUE THREAD

**Issue by hayatae** [node-influx/node-influx#146]
InfluxDB is returning this module warnings when it executes commands such as 'DROP CONTINUOUS QUERY' and 'CREATE CONTINUOUS QUERY' because it seems to be using HTTP GET instead of HTTP POST. According to the warning, executing these commands via GET will be deprecated and should be changed.

Example warnings:
deprecated use of 'DROP CONTINUOUS QUERY "1m" ON "Example Site"' in a read only context, please use a POST request instead
deprecated use of 'CREATE CONTINUOUS QUERY "5s" ON "Example Site" BEGIN SELECT mean.....' in a read only context, please use a POST request instead

**Comment by connor4312** [comment]
Fixed in https://github.com/node-influx/node-influx/pull/188
