### ISSUE TITLE
Verify influxDB connection when starting node application

### ISSUE THREAD

**Issue by SamuelToh** [node-influx/node-influx#153]
Hi,

I have a nodeJS application that depends on the influxDb on start up. So I'm just wondering whether is there already an API on node-influx that would allow me to test for the database's availability? 

I'm looking for some sort of ping API which influxDb has already got support for it.

See
https://docs.influxdata.com/influxdb/v0.13/concepts/api/

Under /ping

Any advise on this problem will be greatly appreciated.

Thanks,
Sam

**Comment by SamuelToh** [comment]
Not critically important.

Found a temporary workaround by throwing in a simple "show databases" query to test whether the port is ready for request accepting or not.

**Comment by connor4312** [comment]
There's not currently ping functionality in this library, but that's something we may add. Note node-influx does handle connection availability, including backing off temporarily inaccessible servers, so you shouldn't have to worry _too_ much about checking availability manually while your app is running.

**Comment by SamuelToh** [comment]
@connor4312 Thanks man. Noted your point. 

I'll leave it open as it is labelled as a possible enhancement.

**Comment by connor4312** [comment]
This has been resolved in https://github.com/node-influx/node-influx/commit/710ab50780978065633b8450477aff51cf9147f9, you see the docs for it here! https://node-influx.github.io/class/src/index.js~InfluxDB.html#instance-method-ping

**Comment by connor4312** [comment]
These changes have been published in `5.0.0-alpha.1`. You can install this via:

```
npm install --save influx@next
```
