### ISSUE TITLE
select query builder

### ISSUE THREAD

**Issue by nichdiekuh** [node-influx/node-influx#16]
I'm thinking about writing a select-query-builder. The function would receive an object defining which fields to select from the series and how to aggregate them.

Although the influx SQL syntax is pretty straight forward, I would find it more useful to define my dynamically built queries in json notation. I imagine it to be similar to the mongo query syntax.

e.g.

``` sql
SELECT MEDIAN(my_col), PERCENTILE(my_col,95) FROM my_series WHERE time > NOW()-2h GROUP BY time(1m);
```

could be become something like this:

``` js
var query = {
  select : [ {'median' : 'my_col'}, {'percentile' : ['my_col',95]}],
  where : [{ time : { 'gt' : 'now()-2h'}]
  group : [{time: '1m'}}
};
dbInflux.query('my_series',query,callback()}
```

This syntax is still far from perfect, but I hope you get the idea. 

`dbinflux.query()` could be tweaked to accept either a raw SQL string or an object.

If it's not suitable for this module, it could also become a separate module which sits ontop of node-influx.

What do you think?

**Comment by ross-nordstrom** [comment]
As a quick follow-up, I've been successfully using `squel` to build up my queries, then just pass those to `node-influx`. I use an object to describe the query, then use some quick code to roll that out against squel. For example:

```javascript
var selects = ["MEAN(foo)", "MIN(foo)", "MAX(foo)"];
var queryObj = squel.select();

_.reduce(selects, function(selectClause) {
  queryObj.field(selectClause);
});

var queryStr = queryObj.toString(); // Throws Error if you didn't build correctly. Like here where I didn't specify a From
```

You can extend this example to make assumptions about some query object provided, and do some things to make it more functional.


Overall, I'm not sure this functionality really NEEDS to be in this lib. It's pretty easy to use squel or similar outside of the influx client.

**Comment by bencevans** [comment]
Agreed I'd like to keep this module as thin as usefully possible and use
third party modules to extend functionality.. Thanks for sharing you're
method!

**Comment by connor4312** [comment]
Reopening, this might become a thing. Discussion here: https://github.com/node-influx/node-influx/issues/197#issuecomment-250373403. Ccing @dandv if he wants to subscribe to this conversation :)

It probably won't get shipped in the 5.0.0 release but is a good candidate for a follow-up feature release.

**Comment by GavinF17** [comment]
Hi @connor4312, I'm not sure whether this should be a separate issue as it is an idea that builds on this. An issue I've been having when using the query function is dealing with possible SQL injection attacks as there doesn't seem to be any way to prevent this unless I'm missing something?

If I'm not just missing some obvious way to deal with this 'out of the box' it might be worth adding string sanitisation into this change to prevent this when you are allowing parameters to be passed in.
 
**Quick example:**
When building a query such as this, which accepts a custom match input passed in by a user & is usually expected to be some valid string like 'test':
`query = 'SELECT * FROM measure1 WHERE field = ' + input`

The user could pass in '\'\'; DROP MEASUREMENT measure1' which will cause the query to delete the measurement straight after running, or pretty much any other Influx query:
`query = 'SELECT * FROM measure1 WHERE field = ''; DROP MEASUREMENT measure1`

squel doesn't deal with this problem either
`query = squel.select()
    .from('measure1')
    .where('field = ?', input)
    .toString();`

Still gives: `SELECT * FROM measure1 WHERE (field = ''; DROP MEASUREMENT 'measure1')`

Not sure if I have explained this clearly so let me know if you need me to clarify, this W3Schools link probably does a better job https://www.w3schools.com/sql/sql_injection.asp

**Comment by connor4312** [comment]
We do have an escaper that allows for safe insertion of external content, check out the [escape object](https://node-influx.github.io/variable/index.html#static-variable-escape).

However, InfluxDB has added support for [bound parameters](https://docs.influxdata.com/influxdb/v1.2/tools/api/#bind-parameters) for safer usage. We should definitely support that in this client.

**Comment by GavinF17** [comment]
Not sure how I managed to miss the escaping, thanks & look forward seeing the new query builder

**Comment by JuanRamino** [comment]
What about this query builder?

[https://github.com/vicanso/influx-ql](https://github.com/vicanso/influx-ql)

**Comment by dominique-mueller** [comment]
not stale
