### ISSUE TITLE
Error: connect ETIMEDOUT or "No host available"

### ISSUE THREAD

**Issue by dandv** [node-influx/node-influx#171]
I'm playing with InfluxDB, writing about 5 points per second individually with `writePoint()`. The payload is small (one field, one tag), but after the script runs for 3-4 minutes, I start getting `connect ETIMEDOUT` or `No host available` errors in the callback. The client is on my local machine and the server is a relatively beefy VPS with 2 CPU cores and 2GB RAM, not running much else.

Has anyone else seen this issue? I haven't found anything at https://github.com/influxdata/influxdb/issues.

I can of course buffer the writes into an array of values and use `writePoints()`, but I thought InfluxDB was designed for high-performance data intake.

**Comment by connor4312** [comment]
This _probably_ isn't a bug in the adapter; ETIMEDOUT will cause the adapter to treat the host as being down, removing it from the connection pool for a certain amount of time, causing the `No host available` error. I would try writing a super simple bash script that writes points with the `curl` command and see if you get time outs there...

**Comment by strongpauly** [comment]
We saw a similar situation when connecting to an influx cloud instance.  Their support team recommended that we batch our writes as much as we can.  It appears that influx doesn't like lots of small posts.

**Comment by dandv** [comment]
I've batched my writes so go 100 points at a time (once every 1 to 10 seconds), and indeed, the ETIMEDOUT is gone.

I do get `Error: getaddrinfo EAI_AGAIN` every ~15 minutes though, and I see no reason why the DNS would be down. My network is rock solid. However, after replacing the hostname with its IP, I no longer got the error.

**Comment by dandv** [comment]
Even with batching, the host still ends up being down - see #178.

**Comment by dandv** [comment]
@connor4312:
> I would try writing a super simple bash script that writes points with the curl command and see if you get time outs there...

I wrote this bash script, and the equivalent loop using my isomorphic-fetch branch:

```sh
#!/bin/bash
for i in {1..1000}
do
  echo -n "$i "
  curl 'https://wiki.dandascalescu.com:12345/query' -u dandv:XXX --data-urlencode 'db=test' --data-urlencode "q=SELECT value FROM series LIMIT 1 OFFSET $i" -s -o output.txt
done
```

This ran flawlessly. The 'test' measurement was just the numbers 0 thru 999, one second apart:

```js
  for (let i = 0; i < n; i++) {
    points.push([
      {
        time: Date.now() - i * 1000,
        value: i
      },
      {foo: 'bar'}
    ]);
  }
```

Here is the equivalent of the bash script using the module:

```js
import InfluxPlus from '../lib/influxplus';
const influx = new InfluxPlus({
  hosts: ['https://wiki.dandascalescu.com:12345'],
  username: 'dandv',
  password: 'XXX',
  database: 'test',
  requestTimeout: 20000,
  failoverTimeout: 40000
});

async function stressTest(n) {
  for (let i = 0; i < n; i++) {
    try {
      let r = await influx.qRaw(`SELECT value FROM series LIMIT 1 OFFSET ${i}`);
      console.log(i, r[0].series[0].values);
    } catch (error) {
      console.error(error);
    }
  }
}

stressTest(1000);
```

(The implementation of qRaw is a simple Promisifying wrapper which I swear I posted [here](https://github.com/node-influx/node-influx/issues/165#issuecomment-250994505) but I no longer see it.)

Anyway, the script above dies with `FetchError: network timeout` after ~70 to 200 calls out of 1000 (I tried several times). Then the host becomes unavailable and the loop dumps tens of "Error: No host available" stack traces.

This happened before, using the request module, and it happens with node-fetch as well.

Can you reproduce? What about with v5?

**Comment by connor4312** [comment]
That's quite weird. I've not gotten to the point of actually writing data yet in 5.0.0 (that's for this evening!) but I'll try to repro this weekend on both 4.x and 5.x.

**Comment by bcatalin** [comment]
I also encounter this issue very often now. I have only 17 millions records of data from sensors (like 20 measurements per second per sensor). I cannot write in batch since the inserted data from DB is crucial.


```
Error saving data to InfluxDB! Error: No host available
    at ServiceNotAvailableError.Error (native)
    at new ServiceNotAvailableError (/root/RAM/ramserver/node_modules/influx/lib/src/pool.js:37:28)
    at Pool.stream (/root/RAM/ramserver/node_modules/influx/lib/src/pool.js:254:29)
    at /root/RAM/ramserver/node_modules/influx/lib/src/pool.js:186:19
    at Pool.discard (/root/RAM/ramserver/node_modules/influx/lib/src/pool.js:185:16)
    at InfluxDB.writePoints (/root/RAM/ramserver/node_modules/influx/lib/src/index.js:736:26)
    at Socket.<anonymous> (/root/RAM/ramserver/server.js:412:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at /root/RAM/ramserver/node_modules/socket.io/lib/socket.js:503:12
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

Every record is important for the app so is this the right database ? Is Influx ready for IoT ?

**Comment by connor4312** [comment]
If every record is important, time series databases aren't what you're after. [The "Design Insights and Tradeoffs" doc](https://docs.influxdata.com/influxdb/v1.2/concepts/insights_tradeoffs/) specifically call out that in a time series database, "No one point is too important."

**Comment by bcatalin** [comment]
I do have protection for that, getting data from sensors into Influx is more appropriate than using it for a DB tool to track hosts in  network, but it's just my opinion :-)

I also have problems with a simple SELECT COUNT(x) FROM for example.
```
> select count(x) from ram_data
ERR: Get http://localhost:8086/query?db=RAM&epoch=ns&q=select+count%28x%29+from+ram_data: EOF
```
Can you tell me, please, what to do to get the number of measurements from a collection in a safe way?

**Comment by connor4312** [comment]
It looks like your InfluxDB instance is having issues, or the machine it's on is misconfigured. The community support forums would be able to help more if you have questions about operating Influx: https://community.influxdata.com/

**Comment by antonioaguilar** [comment]
I have encountered the same issue after testing influxdb for 14 hours. I'm running influxdb on a Docker container with 8GB memory and inserting data using node-influx. This is a snapshot of my influxdb container:

```
docker stats influxdb --no-stream
CONTAINER           CPU %               MEM USAGE / LIMIT   MEM %               NET I/O             BLOCK I/O           PIDS
influxdb            0.08%               3.067 GiB / 8 GiB   38.34%              1.53 GB / 790 MB    299 MB / 12.3 GB    20
```

Here is a snapshot of ```debug/vars``` output:

```javascript
system: {
  currentTime: "2017-07-10T07:38:51.163696947Z",
  started: "2017-07-09T17:35:42.747324136Z",
  uptime: 50588
},
... truncated ...
httpd::8086: {
  name: "httpd",
  tags: {
    bind: ":8086"
  },
  values: {
    authFail: 0,
    clientError: 1,
    pingReq: 4,
    pointsWrittenDropped: 0,
    pointsWrittenFail: 1005176,
    pointsWrittenOK: 4880048,
    queryReq: 17,
    queryReqDurationNs: 6048525501,
    queryRespBytes: 36960,
    req: 1471517,
    reqActive: 187,
    reqDurationNs: 2566093878908857,
    serverError: 251294,
    statusReq: 0,
    writeReq: 1471492,
    writeReqActive: 186,
    writeReqBytes: 842258725,
    writeReqDurationNs: 2565881211274547
  }
}
```
My influxdb instance has been running for 14 hours approx. and the service that was logging data is now throwing the ```Internal Server Error```. 

```
{ Error: Internal Server Error
    at new ServiceNotAvailableError (/home/owc/repos/aya-logger/node_modules/influx/lib/src/pool.js:37:28)
    at /home/owc/repos/aya-logger/node_modules/influx/lib/src/pool.js:272:49
    at ClientRequest.<anonymous> (/home/owc/repos/aya-logger/node_modules/influx/lib/src/pool.js:79:13)
    at ClientRequest.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:473:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at Socket.socketOnData (_http_client.js:362:20)
    at emitOne (events.js:96:13) message: 'Internal Server Error' }
```
Trying to push data to influxdb via other mechanisms also fail (e.g. using curl):

```
curl -i -XPOST 'http://localhost:8086/write?db=db' --data-binary 'cpu,host=server01,region=us-west value=0.64'
HTTP/1.1 500 Internal Server Error
Content-Type: application/json
Request-Id: 1abedda6-6546-11e7-8308-000000000000
X-Influxdb-Version: 1.3.0
Date: Mon, 10 Jul 2017 08:02:32 GMT
Content-Length: 20

{"error":"timeout"}
```
What is interesting is that I can still access the database and perform queries via the influx CLI. 

```
Connected to http://localhost:8086 version 1.3.0
InfluxDB shell version: 1.2.4
> use db
Using database db
> select count(*) from "memory"
name: memory
time count_used_heap count_used_memory
---- --------------- -----------------
0    1492484         1492484
>
```
But it seems no more data can be pushed to influxdb. Is the community support forums the best place to report this issue?

**Comment by connor4312** [comment]
The Influx community forums can be found here: https://community.influxdata.com/

I would expect that, in your scenario, Inlfux would be logging something that says why it isn't accepting writes.

**Comment by antonioaguilar** [comment]
@connor4312 I created a bug report in https://github.com/influxdata/influxdb/issues/8582

**Comment by SCHKN** [comment]
Node Influx will also raises a "No host available" error when you try to push to a measurement with a certain retention policy, yet you haven't created this retention policy
