### ISSUE TITLE
Doesn't work with Webpack: Error: define cannot be used indirect

### ISSUE THREAD

**Issue by dandv** [node-influx/node-influx#174]
Again [due to the request module](https://github.com/request/request/issues/1920).

webpack.config based on [another webpack workaround for request](https://github.com/request/request/issues/1529#issuecomment-103454943):
```js
module.exports = {
  entry: './src',
  output: {
    path: 'dist',
    filename: 'bundle.js'
  },
  module: {
    loaders: [
      { test: /\.json$/, loader: 'json-loader' }
    ]
  },
  node: {
    console: 'empty',
    fs: 'empty',
    net: 'empty',
    tls: 'empty'
  }
};
```

**Comment by dandv** [comment]
As a workaround, I [downgraded to an older version of `request`](https://github.com/request/request/issues/1920#issuecomment-179904270), but still, there's a new error:

> Credentials flag is 'true', but the 'Access-Control-Allow-Credentials' header is ''. It must be 'true' to allow credentials. Origin 'http://localhost' is therefore not allowed access.

Turns out [the http-browserify module erroneously defaults `withCredentials` to `true`](https://github.com/request/request/issues/986#issuecomment-88490000), and it's been [more than two years](https://github.com/substack/http-browserify/pull/53) since PRs have been sent to fix that - still not merged.

**Comment by connor4312** [comment]
See https://github.com/node-influx/node-influx/pull/202#issuecomment-253964886
