### ISSUE TITLE
Replace request with isomorphic-fetch

### ISSUE THREAD

**Issue by dandv** [node-influx/node-influx#177]
This would enable the module to work in the browser, and would fix #173 and #174.

[Other libraries have done the same.](https://github.com/mapbox/mapbox-gl-geocoder/pull/46)

**Comment by dandv** [comment]
Working on this. Seems the only request-specific capabilities used are `timeout` and `pool`.

[`node-fetch` implements `timeout`](https://github.com/bitinn/node-fetch#options).

[`pool`](https://github.com/node-influx/node-influx/blob/master/index.js#L384) we don't undocument - any background on it?

**Comment by connor4312** [comment]
See https://github.com/node-influx/node-influx/pull/202#issuecomment-253964886
