### ISSUE TITLE
Odd parameter scheme for writePoints(), vs. the docs?

### ISSUE THREAD

**Issue by dandv** [node-influx/node-influx#182]
IMO the way parameters are passed to `writePoints` is a little odd, each point being an array of two objects, with the timestamp being a special field in the first object. This goes against the order specified in the [Line Protocol docs](https://docs.influxdata.com/influxdb/latest/write_protocols/line_protocol_tutorial/#syntax), `measurement,tag1=value1,tag2=value2 field1=value1,field2=value2 timestamp`.

How about an alternative API, where a point can be an object instead of a 2-element array, with a key `fields`, and optional keys `time` and `tags`?

```js
writePoints(measurementName, [
  {
    fields: {value: 123, otherValue: 456},
    tags: {foo: 'bar'},
    time: new Date()
  },
  {
    fields: {foo: 123}  // no tags or timestamp
  },
  {
    fields: 123  // automatically converted to value=123
  },
  [{a: 1}, {b: 2}],  // old school - unclear which is the field and which is the tag
], [options], callback)
```

**Comment by connor4312** [comment]
That sounds like a good improvement to me. I've begun work on a 5.0.0 release in the branch of the same name (though I've not had a chance to push it forward for some time), I'll make a note to add this in there.

**Comment by Apollon77** [comment]
+1 on the idea :-)

And when it comes to "writeSeries" why not add a file "seriesName" in there, Then "writeSeries" is easier too ... or when thinking further: then the "seriesName" is incorporated in the data object and a "write" would be generic because it can be one datapoint or multiple given in the call and works for both.
So thinking of

```
write([
  {
    seriesName: 'blubb',
    fields: {value: 123, otherValue: 456},
    tags: {foo: 'bar'},
    time: new Date()
  }], [options], callback)

```
vs:

> write([
>   {
>     seriesName: 'field1',
>     fields: {value: 123, otherValue: 456},
>     tags: {foo: 'bar'},
>     time: new Date()-x
>   },
>   {
>     seriesName: 'field2',
>     fields: {value: 123, otherValue: 456},
>     tags: {foo: 'bar'},
>     time: new Date()
>   },
>   {
>     seriesName: 'field1',
>     fields: {value: 123, otherValue: 456},
>     tags: {foo: 'bar'},
>     time: new Date()
>   }
> ], [options], callback)

**Comment by dandv** [comment]
I've just looked at [the other Node InfluxDB library](https://github.com/gobwas/influent#usage), and it uses a similar API for writing points to what we're suggesting:

        client.write({
                key: "myseries",
                tags: {
                    some_tag: "sweet"
                },
                fields: {
                    some_field: 10
                },
                timestamp: Date.now()
            })

I think their usage of `key` is ambiguous, and I prefer `seriesName`. Other than that, I think we're on the right track.

> BTW: What's the timeplan for 5.0.0?

I'll let @connor4312 comment on that. I think one big enabler for v5 is pulling in #164.

**Comment by connor4312** [comment]
Yea that seems sane.

I'll say the second of next month as a tentative timeline for a 5.0.0 RC, with a stable release by the end of the month barring any huge issues.

**Comment by dandv** [comment]
The proposed API easily could allows specifying integers easily (see #190), either via an additional element passed into an array instead of a literal for the value, or through an object::

```js
writePoints(seriesName, [
  {
    fields: {
      value: 123,
      integerValue1: [456, 'i'],
      integerValue2: {
        value: 789,
        type: 'integer'
      }
    },
    tags: {foo: 'bar'},
    time: new Date()
  }
], [options], callback)
```

**Comment by andyday** [comment]
seriesName !== measureName.

The name series is used in several places where the name measure should be used.   For instance writeSeries with its current usage is misleading.   A series is a unique combo of retention, measure, and tags.   The way the writeSeries is used is more a write multiple points for multiple measures.   It might be better to merge writeSeries and writePoints with the following usage:

```javascript
writePoints([{
    measure: 'mymeasurename',
    fields: {
        field1: 123,
        field2: 234
    },
    tags: {
        tag1: 'mytag'
    },
    time:  Date.now()
}], ...)
```

**Comment by connor4312** [comment]
Yep, thanks andyday! Last night I drafted out the new writePoints API, you can find it [here](https://github.com/node-influx/node-influx/blob/5.0.0/src/index.ts#L537) (and the Point/WriteOptions types [here](https://github.com/node-influx/node-influx/blob/5.0.0/src/index.ts#L103-L147)). I will, later, add other helper method like `writeMeasurement(name: string, points: Point[], options?: WriteOptions)` so that users don't have to specify measurements manually in every Point.

**Comment by dandv** [comment]
@andyday: correct. I've fixed [some of that](https://github.com/node-influx/node-influx/pull/205) recently, and have just fixed my examples above.

**Comment by andyday** [comment]
@connor4312 the usage of writePoints in your 5.0 branch is great.   @dandv have those changes been published yet?  not seeing them in 4.2.2

**Comment by dandv** [comment]
@andyday: not yes, since the changes are I made are rather cosmetic and v5 is due very soon.

**Comment by connor4312** [comment]
With completion of the write API in https://github.com/node-influx/node-influx/commit/0ef0889605cab3d323ff0b4cf4992757a60472d8 I'm closing this issue. Please feel free to take a read over the docs (and/or code) here and let me know if you've suggestions for improvement: [index.ts#L540](https://github.com/node-influx/node-influx/blob/5.0.0/src/index.ts#L540)
