### ISSUE TITLE
getDatabaseNames throws unnecessary exception 

### ISSUE THREAD

**Issue by doganyazar** [node-influx/node-influx#187]
getDatabaseNames() is throwing an unnecessary exception when influxdb is booting up. 

Right after influxdb initializes http api, it is possible to write to db and query databases but somehow it is missing the values field:
```
curl -i 'localhost:8086/query' --data-urlencode "q=SHOW DATABASES"
{"results":[{"series":[{"name":"databases","columns":["name"]}]}]}
```

But after a couple of seconds, it shows up:
```
curl -i 'localhost:8086/query' --data-urlencode "q=SHOW DATABASES"
{"results":[{"series":[{"name":"databases","columns":["name"],"values":[["_internal"]]}]}]}
```

But the getDatabaseNames is throwing exception if that field is missing which is misleading
```
var names = _.get(results, '[0].series[0].values')
if (!_.isArray(names)) {
      return callback(new Error('bad response from server', results))
}
```

**Comment by connor4312** [comment]
Could you open an issue with replication instructions on the [node influx](https://github.com/influxdata/influxdb) repo? I _could_ have it retry queries, up to a timeout, until `values` is present, but this feels like a hack and smells like an InfluxDB bug to me; either the results should contain an error or the results should be correct.

**Comment by doganyazar** [comment]
I have created an issue on influxdb's repo. 
https://github.com/influxdata/influxdb/issues/7360

**Comment by connor4312** [comment]
In 5.x we no longer throw exceptions, an empty array of database names will be returned instead. This fixes the issue as far as this module is concerned, I think; correcting their respond behavior is on them 😉 

You can install 5.0.0 via:

```
npm install --save influx@next
```
