### ISSUE TITLE
Microseconds should be "u" not "us"

### ISSUE THREAD

**Issue by fuzzelfish** [node-influx/node-influx#189]
type TimePrecision = "ns"|**"us"**|"ms"|"s"|"m"|"h"|"d"|"w"|"m"|"y";

us somehow saves as ns on version 1.0

u works fine if set as parameter

refer to https://docs.influxdata.com/influxdb/v1.0/guides/querying_data/#timestamp-format

**Comment by connor4312** [comment]
Fixed in https://github.com/node-influx/node-influx/commit/c0edc4b2fc96095cb30318c8374e8ff6607f6847

**Comment by connor4312** [comment]
These changes have been published in `5.0.0-alpha.1`. You can install this via:

```
npm install --save influx@next
```
