### ISSUE TITLE
Suggestion for cleaner GitHub history :)

### ISSUE THREAD

**Issue by dandv** [node-influx/node-influx#194]
http://stackoverflow.com/questions/27208042/neat-clean-compacted-git-pr-and-merge-commit-into-one-commit/29958324#29958324

![image](https://cloud.githubusercontent.com/assets/33569/18777400/c7fb83f4-8123-11e6-8590-829df0a8d101.png)

Result:

![image](https://cloud.githubusercontent.com/assets/33569/18777421/eda7964c-8123-11e6-89da-2f4c2b516ded.png)

**Comment by connor4312** [comment]
I'm neutral on squashing/rebasing...

On one hand, it can lead to prettier histories, particularly when PRs contain lots of WIP or revision commits.

On the other hand, it destroys history and can make conflicts messy when merging in branches which were originally branches off a squash-merged branch, and likewise it can make life more difficult for people maintaining forks of repositories who may have eagerly pulled in branches from PRs on the original repo.

What are your thoughts?

**Comment by dandv** [comment]
I haven't personally run into scenarios like those you've described, but how about the [rebase feature released today](https://github.com/blog/2243-rebase-and-merge-pull-requests)?

**Comment by connor4312** [comment]
So, after a bit more evaluation and experimentation, I think squash merges would work well. Gave them a spin at work with good results. I'll update the default setting for this repo, and start doing them from now on.
