### ISSUE TITLE
Nanosecond-precision timestamps

### ISSUE THREAD

**Issue by dandv** [node-influx/node-influx#196]
Currently,

> The time can be either an integer value or a Date object.

This won't allow [nanosecond-precision timestamps](https://github.com/gobwas/influent/pull/1#issuecomment-137720514).

**Comment by connor4312** [comment]
Ideally I would like to support nanosecond-precision everywhere. But, reading data becomes challenging. Influx returns nanosecond-precision timestamps as integers, but `JSON.parse` cannot decode these without losing precision as they're converted to 64-bit floating point numbers. Therefore we would need a custom JSON parser, which makes things slower and much more complicated.

So, nanoseconds work for writing, but I think I'll stick with microsecond precision as the limit for reading, at least for now.

**Comment by connor4312** [comment]
Fixed in 4.x in https://github.com/node-influx/node-influx/pull/204/files

Fixed in 5.x with the completion from https://github.com/node-influx/node-influx/commit/0ef0889605cab3d323ff0b4cf4992757a60472d8

**Comment by connor4312** [comment]
Resolved in 4.2.3

**Comment by connor4312** [comment]
These changes have been published in `5.0.0-alpha.1`. You can install this via:

```
npm install --save influx@next
```
