### ISSUE TITLE
Feedback request: Influx Results

### ISSUE THREAD

**Issue by connor4312** [node-influx/node-influx#200]
I'm working on the query response format for 5.0.0 and was looking to get some feedback on it, that is, what the `results` should look like in `influx.query('select ...', (err, results) => { /* ... */)`.

There are three cases we have to deal with:

#### 1. A single query and simple response

I think we can generally agree it should be returned as an array of objects, having mapped in the columns:

```ts
influx.query('select * from my_series', (err, results) => {
  expect(results).to.deep.equal([
    { my_tag: 'foo', my_integer: 42, time: new Date(...) },
    // ...
  ])
});
```

Unmarshing these results runs about 3x as fast (~4,000,000 rows/sec on my Macbook Air) as the current implementation.

Are there any additional helper methods we would like on here?

#### 2. A grouped response with tag names

Here's my current working status in `5.0.0`. The results are still an array, _but_ you can use `.groups()` to get a list of groups and tag names, and `.group(match)` to look up a certain group:

```ts
influx.query('select top(my_integer, 1) from my_series group by my_tag', (err, results) => {
  expect(results.groups()).to.deep.equal([{
    tags: { my_tag: 'a' },
    rows: [{ top: 32 }],
  }, {
    tags: { my_tag: 'b' },
    rows: [{ top: 53 }],
  }]);

  expect(results.group({ my_tag: 'b' })).to.deep.equal([
    { top: 32 },
  ]);

  expect(results.group({ my_tag: 'not_existent' })).to.deep.equal([]);
});
```

Unmarshing these results are about 15x faster (~1,400,000 groups/sec) than the current implementation. `.groups()` calls are free and `.group(matcher)` lookups run at about 60,000 ops/sec on result sizes up to 10k groups.

#### 3. Multiple queries

Multiple queries will be returned as arrays of the "Result" types handled in case 1 and 2

#### 4. Special case: streaming

Streaming results will be supported via a separate API ;)

**Comment by dandv** [comment]
Looks good, as long as we preserve queryRaw, for those odd cases when arrays of arrays are required, instead of arrays of objects. Highcharts is one example of this - to plot a simple time series, it wants and array of 2-element arrays, `[time, value]`.

Because of that, I've found myself processing the results of queryRaw like this:

```js
influx.queryRaw(`SELECT foo, bar FROM ${self.measurement}`, function (err, results) {
  let columns = results[0].series[0].columns;
  let values = results[0].series[0].values;
  let indexes = {};
  for (const colName of columns) indexes[colName] = columns.indexOf(colName);
  let data = [];
  for (const point of values) {
    data.push([
      new Date(point[indexes.time]).getTime(),
      point[indexes.foo]
    ]);
  }
  // ... plotting
);
```
A useful convenience method from Meteor/MongoDB was [findOne](https://docs.meteor.com/api/collections.html#Mongo-Collection-findOne), which returns the object you want directly and applies a `LIMIT 1` automatically.

Regarding performance, I think the network request will be the bottleneck, but it's good to see the improvements you've made.

**Comment by connor4312** [comment]
Preserving queryRaw makes sense. If nothing else, so that people can use new features or features that we miss in the primary API without waiting for us to accept and PR and release a new version. With what you're doing there, however, you should be able to simply do this...

```js
influx.query(`SELECT foo, bar FROM ${self.measurement}`).then(results => {
  const data = results.map(point => [point.time, point.foo]);
  // ... plotting
);
```

`findOne` is definitely a useful method to have. It's less useful in a time series application like Influx, but still nice for single datapoints like the overall `mean` of a set.

Network requests are a bottleneck, but particularly we _really_ want to avoid doing computation on the main thread in Node. Things that happen here stop the world while they're running, whereas network operations are outside the event loop and don't directly reduce application throughput. That's my background for having performance within the library being a concern, even though it is greatly overshadowed by network latency and time within Influx.

**Comment by dandv** [comment]
> With what you're doing there, however, you should be able to simply do this...

Right. I was using `queryRaw` there for performance reasons, to not go through query's deserialization, and then make another pass over the results array.

**Comment by connor4312** [comment]
Ah, fair enough. I would _like_ to be able to do permit streaming results--with a streaming JSON parser--however the existing implementations of this for Node are quite slow, slower than parsing all but the largest result sets in one go and iterating over them again... Further investigation is needed there, but if possible I would like to provide streaming as a separate method/API.
