### ISSUE TITLE
Issue with HTTPS when using injected root certificate authorities

### ISSUE THREAD

**Issue by RobertTheProfessional** [node-influx/node-influx#206]
I noted the the certificates in the `https.globalAgent.options.ca` array are ignored when using the `.writeSeries` function but are properly used when the `.getDatabaseNames` function is called. I tracked the issue to the way that the HTTPS request is made. When the POST is made with request the the pool key in the request options is set to an empty object if a pool isn't passed as a parameter; which causes the request module to fail a conditional that is supposed to return the globalAgent. The object should be set to `undefined` if a pool isn't passed a parameter to ensure that the globalAgent is always returned.

![requests-conditional](https://cloud.githubusercontent.com/assets/1852571/19166005/f7123592-8bd3-11e6-8ebe-ebcd9f24746e.png)

**Comment by connor4312** [comment]
Resolved in 4.2.3
