### ISSUE TITLE
Integrate nodesecurity.io checks?

### ISSUE THREAD

**Issue by dandv** [node-influx/node-influx#212]
https://npms.io/search?q=influx marks insecure packages by running [`nsp`](https://www.npmjs.com/package/nsp) `check`.

I've run nsp and there were no vulnerabilities encountered.

https://nodesecurity.io/ offers a free service for open source projects.

**Comment by connor4312** [comment]
Hey, I've actually integrated Bithound badges / analysis into the project (previously for a code quality metric we were using CodeClimate, but they don't well support TypeScript yet). They have dependency analysis which uses nsp -- there's now a badge on the readme!
