### ISSUE TITLE
Inconsistent constructor docs

### ISSUE THREAD

**Issue by dandv** [node-influx/node-influx#218]
Probably already on your radar, but the constructor invocation at https://node-influx.github.io/class/src/index.js~InfluxDB.html differs from the one [farther down the page](https://node-influx.github.io/class/src/index.js~InfluxDB.html#instance-constructor-constructor). The second one should also probably import or qualify FieldType.

**Comment by offero** [comment]
I have also been confused by this.

**Comment by connor4312** [comment]
Resolved in b0af574

**Comment by connor4312** [comment]
Published in `5.0.0-alpha.2`, available under `npm install --save influx@next`
