### ISSUE TITLE
Complete method coverage of all Influx statements

### ISSUE THREAD

**Issue by connor4312** [node-influx/node-influx#222]
Ongoing todo, ideally should have most of these in 5.1.0 but 100% coverage will not be prioritized over enhancing the experience for the most common use cases. Adding these is more tedious than intricate and PRs are more than welcome! 😄 
- [x] `alter_retention_policy_stmt`
- [x] `create_continuous_query_stmt`
- [x] `create_database_stmt`
- [x] `create_retention_policy_stmt`
- [ ] `create_subscription_stmt`
- [x] `create_user_stmt`
- [ ] `delete_stmt`
- [x] `drop_continuous_query_stmt`
- [x] `drop_database_stmt`
- [x] `drop_measurement_stmt`
- [x] `drop_retention_policy_stmt`
- [x] `drop_series_stmt`
- [x] `drop_shard_stmt`
- [ ] `drop_subscription_stmt`
- [x] `drop_user_stmt`
- [x] `grant_stmt`
- [ ] `kill_query_statement`
- [x] `show_continuous_queries_stmt`
- [x] `show_databases_stmt`
- [ ] `show_field_keys_stmt`
- [ ] `show_grants_stmt`
- [x] `show_measurements_stmt`
- [ ] `show_queries_stmt`
- [x] `show_retention_policies`
- [x] `show_series_stmt`
- [ ] `show_shard_groups_stmt`
- [x] `show_shards_stmt`
- [ ] `show_subscriptions_stm`
- [ ] `show_tag_keys_stmt`
- [ ] `show_tag_values_stmt`
- [x] `show_users_stmt`
- [x] `revoke_stmt`
- [x] `select_stmt`

Pulled from the [query language spec](https://docs.influxdata.com/influxdb/v1.0/query_language/spec) on Oct 17th

**Comment by Infern1** [comment]
Can be updated:
see: dropShard: 
https://github.com/node-influx/node-influx/pull/418
showShard
https://github.com/node-influx/node-influx/pull/415
