### ISSUE TITLE
Package can't be used as a GitHub dependency

### ISSUE THREAD

**Issue by dandv** [node-influx/node-influx#224]
Trying to test the req.setTimeout workaround for Webpack, I've added [the GitHub URL](https://docs.npmjs.com/files/package.json#github-urls) to `package.json`,

```json
  "dependencies": {
    "influx": "node-influx/node-influx"
  },
```

but no source files get donwloaded in `node_modules`, due to [this npm limitation](https://github.com/npm/npm/issues/3055#issuecomment-222897703).

Will wait for the next npm release.

**Comment by connor4312** [comment]
I've created a `5.x-dist` branch with the compiled JavaScript files, that should work.

**Comment by dandv** [comment]
That did work, thanks!
