### ISSUE TITLE
res.setEncoding is not a function

### ISSUE THREAD

**Issue by dandv** [node-influx/node-influx#225]
[In pool.js](https://github.com/node-influx/node-influx/blob/master/src/pool.ts#L92), using Webpack 2.

**Comment by connor4312** [comment]
Fixed in https://github.com/node-influx/node-influx/commit/3311efa389a6abef31300c26afe83470701aa4ff, I'll push a new build to the dist branch tonight for you.

**Comment by connor4312** [comment]
Published in `5.0.0-alpha.2`, available under `npm install --save influx@next`
