### ISSUE TITLE
Add browser-based tests

### ISSUE THREAD

**Issue by dandv** [node-influx/node-influx#226]
...using Webpack and ideally jspm too, given #221, #225 and the like.

BTW, after guarding #225, Pool.json() dies with "Unexpected end of JSON input" when `res` is the empty string. While that sounds like the [bug I filed with node-fetch against handling 204 No Content results](https://github.com/bitinn/node-fetch/issues/165), a different error should be raised in that case because of this ([misleading](https://bugs.chromium.org/p/chromium/issues/detail?id=566239#c8)) XHR error:

> XMLHttpRequest cannot load http://localhost:8086/query?.... Credentials flag is 'true', but the 'Access-Control-Allow-Credentials' header is ''. It must be 'true' to allow credentials. Origin 'http://localhost:8080' is therefore not allowed access.

**Comment by connor4312** [comment]
Started work on this in https://github.com/node-influx/node-influx/commit/cbf13700bb03881dd331ed3228b8479df508f5cb. Karma runs but the pool tests, I'll address those tomorrow.

**Comment by connor4312** [comment]
🎉 

![](https://saucelabs.com/browser-matrix/connor4312.svg)

**Comment by connor4312** [comment]
Published in `5.0.0-alpha.2`, available under `npm install --save influx@next`
