### ISSUE TITLE
FieldType Missing

### ISSUE THREAD

**Issue by j-Nimble** [node-influx/node-influx#230]
The tutorials and the documentation mention using the 'FieldType' structure to specify the data type for fields.  I just downloaded version 4.2.3 and that data structure is not present in the Influx module.  Everytime I try to reference it it says undefined and actually looking through the installed packages (installed via NPM), those words are not in there.  I looked through the change log to see if it was present in a newer version, but I didn't see anything relating to 'FieldType'.  I apologize for cluttering up the issues section, but any assistance would be greatly appreciated.

**Comment by j-Nimble** [comment]
Apparently, it was added in version 5.0.0 or something like that, upgrading to the alpha3 solved the issue.

**Comment by connor4312** [comment]
Yep, that's the cause 👍  5.0.0 stable should be releasing within the next week.
