### ISSUE TITLE
Using node-influx Meteor client side

### ISSUE THREAD

**Issue by ericvrp** [node-influx/node-influx#236]
This might be a useful addition to https://node-influx.github.io/manual/usage.html#browser-setup

I got node-influx working in the browser of my Meteor project by doing the following.

```
npm install --save node-influx/stream-http meteor-node-stubs
ln -s stream-http node_modules/http
ln -s stream-http node_modules/https
```

Of course it would be much nicer if we could somehow (in packages.json?) specify the http/https aliasing of stream-http. But for anyone using this package in Meteor this information might be a good start. I could make a pull request if you want.

**Comment by connor4312** [comment]
I've never touched Meteor before, but it sounds like it should be something that's overridden in the `packages.json`. A big part of package managers is allows for reproducible builds, and having to manually symblink (or symblink at all -- `ln -s` won't work on Windows outside of Cygwin which npm doesn't technically support) breaks that. If possible it'd be awesome if you could PR something along those lines! 😄

**Comment by ericvrp** [comment]
I don't have Windows access. I agree that my solution is not what we want in the end. But there are other things for me to do at the moment so I hope someone else will pick up this issue.

**Comment by bencevans** [comment]
We aren't aware of any other use from meteor and none of the core developers are currently using meteor. A pull-request to the code or adding documentation detailing the process of using node-influx with meteor is very welcome however will not be contributed by the team.
