### ISSUE TITLE
Typo in Documentation

### ISSUE THREAD

**Issue by Santinell** [node-influx/node-influx#238]
For method createRetentionPolicy
in documentation "options.default", but using "options.isDefault"

node-influx v5.0.0

**Comment by connor4312** [comment]
Resolved in https://github.com/node-influx/node-influx/commit/023af8bed00798eb80d244d68f761602fe015a4f

**Comment by Santinell** [comment]
To be honest Documentation for method `alterRetentionPolicy` have the same problem.
I did't notice it, because I don't use it.
