### ISSUE TITLE
Bug in grantPrivilege

### ISSUE THREAD

**Issue by Santinell** [node-influx/node-influx#239]
For this request
`influxDb.grantPrivilege('571dbd9672379792340f87d2', 'WRITE', 'test');`
I get this error

```
Unhandled rejection Error: A 400 Bad Request error occurred: {"error":"error parsing query: found TO, expected ON at line 1, char 13"}
```

But in the same time this works:
`influxDb.query('GRANT WRITE ON test TO "571dbd9672379792340f87d2"', {database: 'test'});`

node-influx v5.0.0
influx v1.0.2

**Comment by connor4312** [comment]
Thanks! I'll get a fix in for this tonight.

**Comment by connor4312** [comment]
Resolved in https://github.com/node-influx/node-influx/commit/6f2d6edf1413128a2a89541b78189f5589f5edf1
