### ISSUE TITLE
Timestamps set to 1970-01-01

### ISSUE THREAD

**Issue by dennisbauer** [node-influx/node-influx#240]
I'am using node-influx 5.0.1 with InfluxDB 1.0.2 on Ubuntu 14.04. Trying to write the following point

```
{ measurement: 'test',
    tags: { meta: 'test' },
    fields: { test: 1.5 },
    timestamp: 1479224298038 } ]
```
everything is stored in InfluxDB as 1970-01-01. 
When adding writeOptions as `precision: 'ms'` nothing arrives in InfluxDB but also no error is thrown. When omitting the timestamps in written points and using system time instead, everything is working fine. Am I doing something wrong or might this be an issue?

**Comment by connor4312** [comment]
> Trying to write the following point... everything is stored in InfluxDB as 1970-01-01.

That's correct behaviour; timestamps in InfluxDB are stored in nanoseconds, `1479224298038` nanoseconds after the unix epoch corresponds to `1970-01-01T00:24:39.224Z`. If you're passing in raw numbers, you should specify a precision.

> When adding writeOptions as precision: 'ms' nothing arrives in InfluxDB but also no error is thrown.

I can't reproduce this issue. Using the following script:

```
const Influx = require('./').InfluxDB;
const db = new Influx();

db.writePoints([
  { measurement: 'test',
    tags: { meta: 'test' },
    fields: { test: 1.5 },
    timestamp: 1479224298038 }
], {
  precision: 'ms',
  database: 'test',
});
```

It writes data to Influx as expected:

```
> select * from test;
name: test
----------
time			meta	test
1479224298038000000	test	1.5
```

Can you provide reproduction instructions?

**Comment by dennisbauer** [comment]
I'm using basically the same script as you did. But every time i specify write options, nothing happens - no error message, no entry to database.

```
const Influx = require('influx');
const influx = new Influx.InfluxDB({
        host: hostname,
        database: databasename,
        port: 8086,
    });

influx.writePoints([
  { measurement: 'test',
    tags: { meta: 'test' },
    fields: { test: 1.5 },
    timestamp: 1479224298038 }
], {
  precision: 'ms',
  database: 'test',
});
```

**Comment by connor4312** [comment]
I would try either using something like Fiddler to examine the http traffic or console.log the status code [here](https://github.com/node-influx/node-influx/blob/master/src/pool.ts#L352). If it's a 1xx or 2xx code that means that Influx said that it wrote the data successfully. If that's the case, then the issue is in Influx or your Influx configuration.

**Comment by dennisbauer** [comment]
Thanks! I logged the status code and it's 204. On a new InfluxDB installation everything is running fine.
