### ISSUE TITLE
TLS Support

### ISSUE THREAD

**Issue by devcrust** [node-influx/node-influx#241]
In many cloud based environments, SSL/TLS is mandatory (at least from a customer's point of view).

It might be already enough if the IClusterConfig and ISingleHostConfig interfaces could be extended in order to support the TLS options from [tls.connect()](https://nodejs.org/dist/latest-v7.x/docs/api/tls.html#tls_tls_connect_options_callback)

In detail:

- pfx: Certificate, Private key and CA certificates to use for SSL. Default null.
- key: Private key to use for SSL. Default null.
- passphrase: A string of passphrase for the private key or pfx. Default null.
- cert: Public x509 certificate to use. Default null.
- ca: A string, Buffer or array of strings or Buffers of trusted certificates in PEM format. If this is omitted several well known "root" CAs will be used, like VeriSign. These are used to authorize connections.
- ciphers: A string describing the ciphers to use or exclude. Consult https://www.openssl.org/docs/man1.0.2/apps/ciphers.html#CIPHER-LIST-FORMAT for details on the format.
- rejectUnauthorized: If true, the server certificate is verified against the list of supplied CAs. An 'error' event is emitted if verification fails. Verification happens at the connection level, before the HTTP request is sent. Default true.
- secureProtocol: The SSL method to use, e.g. SSLv3_method to force SSL version 3. The possible values depend on your installation of OpenSSL and are defined in the constant SSL_METHODS.
- servername: Servername for SNI (Server Name Indication) TLS extension.

**Comment by connor4312** [comment]
Thanks for the issue, sorry for the late reply! I've added support for this on what will be my working 5.1.0 branch in https://github.com/node-influx/node-influx/commit/8d752cd11f5a32183d318b0be160457e3e9413ca. Let me know if that works for you.

**Comment by devcrust** [comment]
Excellent, thank you so much!
