### ISSUE TITLE
Error when trying to write a simple JSON object

### ISSUE THREAD

**Issue by ATGardner** [node-influx/node-influx#242]
The following code fails to write a point - [gist](https://gist.github.com/ATGardner/316a288d4ec251e4f30ad6e7f5c8b0eb)

I am using the latest 5.0.1 release from npm, though I had encountered this problem even before updating, while running on 4.2.0 (the code was a bit different).

It currently tries writing `"{"a":"{\"b\":\"c c\"}"}"`, which is the result of `JSON.stringify({a: JSON.stringify({b: 'c c'})})`. The problem seems to be with the space between the two "c" characters, as the working example works (with a "-" between them).

The error I get is
_A 400 Bad Request error occurred: {"error":"unable to parse 'test msg=\"{\\\"a\\\":\\\"{\\\\\"b\\\\\":\\\\\"c c\\\\\"}\\\"}\"': bad timestamp"}_
But I think that the payload should be _test msg="{\"a\":\"{\\\"b\\\":\\\"c c\\\"}\"}"_ - when I use that to insert data from the admin interface, it works as expected.

**Comment by connor4312** [comment]
Thanks for the report! Fixed in 0484f35 and published in 5.0.2.
