### ISSUE TITLE
Unexpected token: .then(data => {

### ISSUE THREAD

**Issue by mathcoll** [node-influx/node-influx#251]
Hello,
I'm facing an issue using 'influx' library.
The script run fine on development environment, but on production server, stack trace returns:
```
.then(data => {
            ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

Does the error have something related to what we are calling "Arrow function" ?
Both env. are really different version, so I don't know which one should be updated (I really bet my issue is related to incompatible libs) and which application...

1. development:
> node -v => v4.2.6
> nodejs -v => v4.2.6
> npm -v => 3.7.1
> lsb_release -r => Release:	16.04 (It's a Xubuntu)
> npm install influx@next => influx@5.0.0-alpha.4

2. production:
> influx -version => InfluxDB shell version: 1.1.1
> node -v => v0.10.29
> nodejs -v => v0.10.29
> npm -v => 1.4.21
> lsb_release -r => Release:	8.0 (Debian)
> npm install influx@next => influx@5.0.0-alpha.4

PS: the full script I'm using for testing:
```
var influx			= require('influx');
var squel			= require('squel');
var influxSettings	= { host : '192.168.0.22', port : 8086, protocol : 'http', username : '', password : '', database : 't6dev' }
var dbString		= influxSettings.protocol+'://'+influxSettings.host+':'+influxSettings.port+'/'+influxSettings.database;
var dbInfluxDB		= new influx.InfluxDB(dbString);
var query = squel.select()
	.field('time, value')
	.from('test')
	.limit(50)
	.offset(1)
	.order('time', true)
;
var list = new Array(1,2,3,4,5,6,7,8,9,10);
list.map(function(i) {
	dbInfluxDB.writePoints([{
		measurement: 'test',
		tags: {id:i},
		fields: {value: 'VALUE'+i},
	}]);
});
dbInfluxDB.query(query.toString())
.then(data => {
	if ( data.length > 0 ) {
		data.map(function(d) {
			d.id = Date.parse(d.time);
			console.log(d.id);
			console.log(d.time + ' ==> ' + d.value);
			console.log('-------\n');
		});
	} else {
		console.log({code: 1, query: query, err: err});
	}
})
.catch(err => {
	console.log({code: 2, query: query, err: err});
});
```

**Comment by connor4312** [comment]
node-influx supports all supported Node versions--those which are not [end of life](https://github.com/nodejs/LTS). 0.10 reached EOL late last year, I _strongly_ recommend that you upgrade your production servers as any security vulnerabilities in 0.10 will no longer be patched, not to mention the bugfixes and speed improvements you'll get on newer Node versions.
