### ISSUE TITLE
A typo in docs of IPoint

### ISSUE THREAD

**Issue by mrkvon** [node-influx/node-influx#252]
A small error in [documentation](https://node-influx.github.io/typedef/index.html#static-typedef-IPoint):
[/src/doc.ts#L219](
https://github.com/node-influx/node-influx/blob/cc02c4d46a49f8b626063388a2b54f58ae868541/src/doc.ts#L219) should say `[timestamp]` instead of `[fields]`.

**Comment by connor4312** [comment]
Thanks for the issue! @dandv fixed this in his recent PR.
