### ISSUE TITLE
Pool.js needs a way to specify a https.request CA option (certificate root)

### ISSUE THREAD

**Issue by maiorfi-at-innovactive** [node-influx/node-influx#262]
At this time I "patched" pool.js loading a ca file with:

```javascript
var requestOptionsCA=fs.readFileSync('ca.cert');

var request = function (options, callback) {
    if (options.protocol === 'https:') {
        options.ca=requestOptionsCA;
        return https.request(options, callback);
    }
    else {
        return http.request(options, callback);
    }
};
```

...but it is far from being the best solution 😄 

This is mandatory in order to connect for example to aiven.io InfluxDB instances.

**Comment by connor4312** [comment]
Heyo. Sorry for the delay, I've added this ability in 5.0.5, allowing you to specify the host options in the [constructor config](https://node-influx.github.io/typedef/index.html#static-typedef-IClusterConfig). You can now handle it something like this:

```js
const influx = new InfluxDB({
  hosts: [{
    host: '127.0.0.1',
    port: 1337,
    options: { ca: requestOptionsCA },
  }]
});
```

The `options` get merged down into the options passed to http.request. Let me know if you hit any more snags, thanks for opening the issue!

**Comment by maiorfi-at-innovactive** [comment]
Hi, first and foremost thanks for your support 😄 

Concerning this issue, I think that InfluxDB ctor actually deletes options property in its "defaulting" function.

I think it should actually do:

```typescript
const resolved = <IClusterConfig> options;
    resolved.hosts = resolved.hosts.map(host => {
      return defaults({
        host: host.host,
        port: host.port,
        protocol: host.protocol,
        options: host.options, /* ADDED */
      }, defaultHost);
    });
```

**Comment by connor4312** [comment]
Whoops, thanks for the catch. I've fixed this (and added a requisite test case 😉 ) in b7f0bb7, which will be published in a few hours.
