### ISSUE TITLE
Support writing points using basic authentication

### ISSUE THREAD

**Issue by emmenko** [node-influx/node-influx#264]
As far as [I can see](https://github.com/node-influx/node-influx/blob/master/src/index.ts#L994-L999) the `username`  and `password` are used as URL query parameters as [HTTP authentication](https://docs.influxdata.com/influxdb/v1.2/tools/api/#example-3-write-a-point-to-the-database-mydb-using-http-authentication).

https://github.com/node-influx/node-influx/blob/master/src/index.ts#L994-L999
![image](https://cloud.githubusercontent.com/assets/1110551/23723187/8bf27d06-0448-11e7-95ce-71eb42a18277.png)

I've noticed this by accident when looking at the logs, which are sent to an external service. The problem I see here is that `username` and `password` are visible in the logs as _plain text_.

However InfluxDB supports also [requests with basic authentication](https://docs.influxdata.com/influxdb/v1.2/tools/api/#example-4-write-a-point-to-the-database-mydb-using-basic-authentication), which would be preferred when dealing with logs.

Any plan to support this or any feedback about this topic?

Thanks

**Comment by taskinosman** [comment]
+1

**Comment by tjyrkinen** [comment]
The InfluxDB constructor supports an option "options" of type http.RequestOptions which is merged into the options passed to the Node http/https request method when points are written.

You can use basic auth by constructing the client like so:
```javascript
client = new Influx.InfluxDB({
  host: 'influxexample.com',
  database: 'mydatabase',
  protocol: 'https',
  options: {
    headers: {
      'Authorization': 'Basic ' + Buffer.from(username + ':' + password).toString('base64')
    }
  }
})
```

**Comment by jmarceli** [comment]
It seems that in **^5.0.0-alpha.4** `options` in the constructor are no longer supported, check the interface implementation https://github.com/node-influx/node-influx/blob/0761e1f37799d8459906723a58292308721b6b41/src/index.ts#L50
What is more request method has hardcoded headers (only `content-length` header exists) see: https://github.com/node-influx/node-influx/blob/0761e1f37799d8459906723a58292308721b6b41/src/pool.ts#L356

**Comment by tspoeri** [comment]
The issue still exists and makes it impossible to use node-influx for writing to telegraf's InfluxDB Listener Input Plugin (https://github.com/influxdata/telegraf/tree/master/plugins/inputs/influxdb_listener) with basic auth enabled.
Any chance basic auth support will be added in the future?

**Comment by bencevans** [comment]
I won't be developing this feature but a PR is welcome. Otherwise I'd recommend looking into the official Influx JS Client.

**Comment by tspoeri** [comment]
Thanks for the info, so I will most probably migrate to the official client
