### ISSUE TITLE
Babel module imports stopped working after upgrade from 5.0.4 to 5.0.5

### ISSUE THREAD

**Issue by josser** [node-influx/node-influx#266]
Hi, 

for some reason this code: 

```javascript
import Influx from 'influx';
```

stopped working after upgrading from 5.0.4 to 5.0.5 (or 5.0.6)
I'm using babel and I'm not sure that this is not configuration issue. 
I've setup test repo where you can make fast test. 
https://github.com/josser/influx_update_issue

Try to change version in package.json to 5.0.5 or 5.0.6 and run:
```
node start.js
```

Thank you and sorry for my bad english.

**Comment by atorkhov** [comment]
Confirming issue.

**Comment by mythfish** [comment]
same issue, any update?

**Comment by joway** [comment]
when i used  `const Influx = require('influx')` it works  .

**Comment by Coriou** [comment]
`import { InfluxDB, FieldType } from 'influx'` ... (and whatever else you want to import) will work
