### ISSUE TITLE
revokePrivilege throws bad request on Influx 1.2.1

### ISSUE THREAD

**Issue by tedhuang** [node-influx/node-influx#268]
Calling InfluxDB.prototype.revokePrivilege (src/index.js :: line 442) yields:

`Error: A 400 Bad Request error occurred: {"error":"error parsing query: found FROM, expected ON at line 1, char 13"}`

InfluxDB version: 1.2.1
Package version 5.0.6

The Fix:

In the same file, line 445 and 446, change:

```
            q: "revoke " + privilege + " from " + grammar.escape.quoted(username) + " on "
                + grammar.escape.quoted(database),
```
to:

```
            q: "revoke " + privilege + " on " + grammar.escape.quoted(database) + 
                + " from " + grammar.escape.quoted(username),
```

**Comment by connor4312** [comment]
Thanks! This is fixed in 5.0.7, which I will publish momentarily.
