### ISSUE TITLE
Can't get epoch timestamps in query() response

### ISSUE THREAD

**Issue by SamAlbuga** [node-influx/node-influx#269]
I can't get query() to return the time like the format you would get in a request with `epoch=s` option.
Can anyone post an example? I'm using an iOS charts library that just requires basic timestamps in seconds! All I'm getting is ISO Timestamps no matter what option I'm passing

**Comment by connor4312** [comment]
Hi Sam,

Dates inside of query responses are marshalled to JavaScript dates, which serialize to ISO dates by default. You should iterate over the response and transform the dates to the format you're after; this isn't something that this client handles for you.

Thanks for opening the issue, let me know if you hit any other snags!

**Comment by BradfordMedeiros** [comment]
@connor4312 is there a reason this isn't in the scope of the client?   There become several shapes the response object can become, and undoubtedly this becomes code nearly all users of this library are going to have to rewrite.

**Comment by SamAlbuga** [comment]
@BradfordMedeiros @connor4312 I've added this as an optional functionality in this pull request #294
