### ISSUE TITLE
Overwriting Existing Records instead of Creating New Ones

### ISSUE THREAD

**Issue by vicatcu** [node-influx/node-influx#272]
I'm getting stuck trying to correct some records in my influx database. I have a tag called 'temperature_units' and a field called 'temperature' and I have accidentally inserted lots of rows that are _actually_ in units of degF but are labelled as units of degC. 

Because influxQL doesn't have an UPDATE statement <groan> I've written a NodeJS script with this library to SELECT all the errant rows from the database with the heuristic "WHERE temperature_units = 'degC' AND temperature > 45" and I'm getting all those rows back. I have more fields than temperature, and I basically have a tag for each field called field_units, plus a serial_number tag.

I then create an array of insert objects like so:

```javascript
return influx.query(`
  select * from data
  where temperature_units = ${Influx.escape.stringLit('degC')}
  and temperature > 45`)
.then((rows) => {
  console.log(`Found ${rows.length} rows`);
  rows.forEach(row => {
    let influxRecord = {
      measurement: 'data',
      tags: {},
      fields: {},
      timestamp:row.time
    };

    // reshape the row into an insert row
    Object.keys(row).filter(k => k !== "time").forEach(k => {
      if(k === 'temperature_units'){
        influxRecord.tags[k] = 'degF';
      }
      else if((k.indexOf("units") >= 0) || k === "serial_number"){
        if(row[k] !== null){
          influxRecord.tags[k] = row[k];
        }
      }
      else{
        if(row[k] !== null){
          influxRecord.fields[k] = row[k];
        }
      }
    });

    recordsToWriteBack.push(influxRecord);
  })
}).then(() => {
  return influx.writePoints(recordsToWriteBack);
}).then(() => {
  console.log("OK. Done.");
});
```

The script succeeds, but then when I go look at my database again from the CLI with some SELECTs, what I can see is that instead of _replacing_ the errant records, I have instead created _new_ records that are identical except that temperature_units is degF instead of degC. 

Please can someone help me to determine the secret sauce I'm missing in order to replace the existing records instead of creating new ones? Is it because the tags have to match as well as the time? In which case I guess I should convert the field instead of the tag?

**Comment by vicatcu** [comment]
Altering the temperature field (through conversion maths) instead of changing the temperature_units field did the trick. I think my reasoning after the fact in the last line of my post was sound. Hopefully someone else can learn from my mistake, closing the issue.

**Comment by connor4312** [comment]
Influx measurements are unique by the tuple of their measurement name (`data`), time, and _tags_. By creating (or altering) a tag called `degF`, you'll be creating new points instead of overwriting old points; for the overwrite to occur, the tags must be identical.

Hope that helps!
