### ISSUE TITLE
Issue creating new connection sessions on timeouts.

### ISSUE THREAD

**Issue by philjestin** [node-influx/node-influx#273]
I am working on a little project where we are listening to a Kafka stream and writing some of the data to an influxdb measurement. In the process we have come acrossed a strange issue with influxdb where node-influx is creating thousands of connections to influxdb.

~: sudo lsof -i -Pn | grep ^node

node      48392       root 4093u  IPv4 326502819      0t0  TCP 10.8.3.28:59442->10.8.3.28:8086 (ESTABLISHED)
node      48392       root 4094u  IPv4 326502820      0t0  TCP 10.8.3.28:59443->10.8.3.28:8086 (ESTABLISHED)
node      48392       root 4096u  IPv4 326502821      0t0  TCP 10.8.3.28:59444->10.8.3.28:8086 (ESTABLISHED)
node      48392       root 4097u  IPv4 326502822      0t0  TCP 10.8.3.28:59445->10.8.3.28:8086 (ESTABLISHED)

So: *There are over 4000 of these*

~: sudo lsof -i -Pn | grep ^node | wc
4328

I believe that node-influx is attempting to establish a new connection wherever there is an error writing to influxdb because of a timeout like in Issue #106 (sorry not sure how to reference issues.)

Logging the errors reported by node-influx with timestamps:

1:51:19 PM - error: Error saving data to InfluxDB's count_stats measurement: Error: connect ECONNREFUSED 10.8.3.28:8086
1:51:19 PM - error: Error saving data to InfluxDB's count_stats measurement: Error: connect ECONNREFUSED 10.8.3.28:8086
1:51:19 PM - error: Error saving data to InfluxDB's count_stats measurement: Error: connect ECONNREFUSED 10.8.3.28:8086
1:51:19 PM - error: Error saving data to InfluxDB's count_stats measurement: Error: connect ECONNREFUSED 10.8.3.28:8086
1:51:19 PM - error: Error saving data to InfluxDB's count_stats measurement: Error: connect ECONNREFUSED 10.8.3.28:8086
1:51:19 PM - error: Error saving data to InfluxDB's count_stats measurement: Error: connect ECONNREFUSED 10.8.3.28:8086

I realize that this is probably poor practice and have started looking into the writePoints API bulk insertion, but still thought that this issue might be worth bringing up.

**Comment by connor4312** [comment]
Your belief is correct; the behavior of the `http` module is to leave connections dangling when a timeout occurs--the timeout is literally just `setTimeout(() => request.emit('timeout'), ...)`. This issue can be resolved by manually closing the `request.connection` when a timeout occurs. I'll throw that on my todo
