### ISSUE TITLE
v5 Does not pass constructor options to https.request

### ISSUE THREAD

**Issue by chrishiestand** [node-influx/node-influx#278]
Expected behavior is as documented here https://node-influx.github.io/typedef/index.html#static-typedef-ISingleHostConfig

I expect that I can pass an options object to the constructor and have that passed on to https.request() - however the options get silently discarded.

You can see that options are missing if you look at pool.js line 251:

```js
var req = request({
            headers: { 'content-length': options.body ? options.body.length : 0 },
            hostname: host.url.hostname,
            method: options.method,
            path: path,
            port: Number(host.url.port),
            protocol: host.url.protocol,
            timeout: this.timeout,
        }
```

So for example, this means that a custom CA certificate cannot be used as in:

```js
const options = {
  servername: 'myhost',
  ca        : [ fs.readFileSync('/tmp/test.ca.crt') ],
}

const influxClient = new Influx.InfluxDB({
  database: 'test',
  host: 'localhost',
  password: 'test',
  port: 8086,
  protocol: 'https',
  username: 'test',
  options,
})
```

**Comment by connor4312** [comment]
What version of node-influx are you using? Support for this was added in 5.0.6, and the code you posted from pool.ts doesn't look like it's updated--it's missing the Object.assign found in the current version<sup>[ref](https://github.com/node-influx/node-influx/blob/master/src/pool.ts#L346)</sup>

**Comment by chrishiestand** [comment]
Ah that must be it. I was following the documentation and ran `npm install --save influx@next` which installed `5.0.0-alpha.4`

Now if I run `npm i --save influx@latest` I get `5.0.7`

**Comment by chrishiestand** [comment]
Also, thanks for your quick response!

**Comment by connor4312** [comment]
I've removed the old `@next` tag from the readme in https://github.com/node-influx/node-influx/commit/56721a63a195405e584928b3ec639dd4ed050533, sorry for the confusion!
