### ISSUE TITLE
Able to access without Password and username in my influx object.

### ISSUE THREAD

**Issue by RiteekS** [node-influx/node-influx#283]
```
const supplyDb = new Influx.InfluxDB({
  host: 'localhost',
  username: supplyDbCredential.username,
  password: supplyDbCredential.password,
  database: 'supply_data',
  schema: [
    {
      measurement: 'supply_data',
      timestamp: 'start_time',
      fields: {
        unique_drivers: Influx.FieldType.INTEGER,
        end_time: Influx.FieldType.INTEGER
      },
      tags: [
        's2_id','s2_id_level','vehicle_type'
      ]
    }
  ]
})
```
If I remove the username and password field also, it works. Where to write username and password for authenticating with db?

**Comment by connor4312** [comment]
If InfluxDB is set up to allow unauthenticated access, then omitting the username and password will allow you to connect. This is expected.

**Comment by RiteekS** [comment]
How to use node-influx to set authenticated access then? I guess by default it is unauthenticated then.

**Comment by connor4312** [comment]
Supplying the username and password in the options as you did is the correct method.
