### ISSUE TITLE
SELECT query compares well on time but returns 1970-01-01T00:00:01.486Z in query result.

### ISSUE THREAD

**Issue by theflyingmantis** [node-influx/node-influx#284]
When I insert the data in my influxDb by write point method, I want to make time field according to my start_time in schema. I am entering the same in epoch.
When I query on time it works well.
```SELECT fruits FROM basket where time>1239904 and time<1244500;```
The result contains array of time and fruits objects.
``` [ {time: 1970-01-01T00:00:01.486Z, fruits: 20}, ...  ]```
But the time is not the time which I entered.

**Comment by connor4312** [comment]
Can you post the code you're using to both insert and retrieve data?
