### ISSUE TITLE
Custom HTTP module support

### ISSUE THREAD

**Issue by mooyoul** [node-influx/node-influx#287]
Hello!

I thought it would be nice if we can modify http/https module.

For example, We're using NewRelic/AWS X-Ray to monitor our applications.
AWS X-Ray SDK provides `AWSXRay.captureHTTPs` methods. this method returns a copy of the http/https module that is patched for collecting metric. ([reference](http://docs.aws.amazon.com/xray-sdk-for-nodejs/latest/reference/AWSXRay.html#.captureHTTPs))

One of major npm packge, request has similar feature. [it can pass http/https module to option object.](https://github.com/request/request/blob/643c43ab7be269a1efaa080ff05a18fff3f64cd7/request.js#L448-L452). i think this approach should be okay in node-influx too.

**Comment by connor4312** [comment]
Unfortunately the grpc implementation for Node is a thin Js layer over over a [core C/++ implementation](https://github.com/grpc/grpc/tree/master/src/core). It doesn't allow consumer to pass their own, and `http(s)?` doesn't support HTTP/2 regardless, which is necessary for grpc.

There is community [interest](https://github.com/grpc/grpc-experiments/issues/159) in a browser version of grpc which would entail a pure JavaScript implementation (and therefore swappable or stub-able libraries), and the Node foundation is working on an [http/2 implementation](https://github.com/nodejs/http2) which may eventually find its way into the core, but it doesn't look like this is possible yet.

Thanks for opening an issue issue!

**Comment by mooyoul** [comment]
I am so sorry that I gave you a wrong explaination.
I mean, just give ability to change http/https module [that using in pool.ts](https://github.com/node-influx/node-influx/blob/452d9d0f8c1a395ae01e9cbb02cc7e02f90284f7/src/pool.ts#L145-L154) to use **wrapped http/https module**, not switching to another protocol like gRPC, SPDY, HTTP/2.

**Comment by connor4312** [comment]
Oh, my bad, I'm so sorry. I was going down my Github notifications and thought this issue was on a different package that I maintain.

Sure, we can do this!
