### ISSUE TITLE
Closing an InfluxDB connection?

### ISSUE THREAD

**Issue by NolanChan** [node-influx/node-influx#289]
Hi! 

I was reading over your documentation and was a bit confused about how to close an InfluxDB connection. Is this possible? (I apologize if I completely missed it in the API).

Thanks!
Nolan

**Comment by MaikelH** [comment]
The underlying connections to influx are based on HTTP requests, which means that there are no long lived connections being kept alive. So it is not necessary to close an connection.

**Comment by NolanChan** [comment]
sounds good, thanks @MaikelH !

**Comment by superhero** [comment]
Also looked for this, could be worth documenting maybe?
