### ISSUE TITLE
Publish native ES module

### ISSUE THREAD

**Issue by dandv** [node-influx/node-influx#298]
Node v8.5.0 has just added experimental support for modules behind a flag, and now [compliant modules](https://github.com/dandv/es-module-example-mjs) can be imported directly, without any transpiler, if they have the `.mjs` extension.

By [omitting the extension in the `main` field of `package.json`](https://stackoverflow.com/questions/46418010/publish-es-module-mjs-to-npmjs-with-backwards-compatibility-for-node-8-5-0), the module will be compatible with Node pre 8.5.0.

**Comment by dandv** [comment]
Update: added [repo](https://github.com/dandv/influx-mjs) showing Node being unable to import the `FieldType` symbol with `--experimental-modules`.

**Comment by dandv** [comment]
Maybe this should be tabled until October, when the `--experimental-modules` flag is expected to drop?

**Comment by bencevans** [comment]
Sounds like a good plan to me. I don't see much point in developing on experimental node flags for node-influx for the time being. Happily accept a PR later along the line though. Closing for now.

**Comment by dandv** [comment]
Any chance to have TypeScript target "esnext"`, now that a few months have passed since Node removed the experimental flag for ES modules?

**Comment by bencevans** [comment]
Great, yes! Please submit a PR :shipit:
