### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by Paxa** [node-influx/node-influx#299]
Is it possible to log all queries and execution time?

Is there some callbacks that I can use?

**Comment by bencevans** [comment]
Not currently but a PR would be very welcome adding this functionality. I think we could make the InfluxDB extend EventEmitter and emit events along the lines of:

```js
client.on('query', (query) => {

})

client.on('query complete', (query, results, metadata = {
  // ...
}) => {

})
```

Or something of the sort. PR welcome but I don't see myself working on this anytime soon.
