### ISSUE TITLE
Bug: synchronous throw not caught by promise

### ISSUE THREAD

**Issue by avimar** [node-influx/node-influx#300]
I ran into this and figured it was a bug.

If you do `return client.writePoints` with some sort of schema mis-match, then the node-influx client will synchronously throw, and it won't be handled by `catch`.

Example:
When the field isn't in the pre-defined list: https://runkit.com/avimar/59e05aaa9d6ebf0012142304
When the field doesn't match the pre-defined type: https://runkit.com/avimar/59e05a990ee0dc0012cced43

But when you wrap it in a `.then` even the sync errors are caught: https://runkit.com/avimar/59e05a070b5d380012db0c20

**Comment by carera** [comment]
Same issue happened to us when trying to write point that does not comply with schema:
```
const defaultInflux = new Influx.InfluxDB({
   ...
  schema: [
    {
      measurement: 'api',
      fields: {
        myField: Influx.FieldType.BOOLEAN
      },
      tags: []
    }
  ]
})
```
    influx.writePoints([{
      measurement: '...',
      fields: {
        myField: 'foo'
      },
      tags: {}
    }])
    .catch(e => logger.error(`influx writing error: ${e.message}`))
```
Throws uncaught
`Error: Expected boolean value for db.api.myField, but got a string!`
