### ISSUE TITLE
JSON parse error thrown while querying to a measurement

### ISSUE THREAD

**Issue by vairabagni** [node-influx/node-influx#301]
const Influx = require('influx');
const dbLogs = new Influx.InfluxDB({
	host: 'localhost',
	database: 'tbl_logs'
});
dbLogs.query(`SELECT * FROM "minute_sum_of_avgs" WHERE time >='2017-11-07T18:30:00.000Z' AND time <='2017-11-08T18:29:59.999Z'`)
.then((rows) => {
	console.log(rows.length);
}).catch((err) => {
	console.log(err, err.toString());
});

This is throwing following error:

SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at *****************\node_modules\influx\lib\src\pool.js:160:69
    at process._tickCallback (internal/process/next_tick.js:103:7) 'SyntaxError: Unexpected end of JSON input'

Then I checked pool JS & found that after getting few chunks it is trying parse the JSON.
![untitled](https://user-images.githubusercontent.com/3302973/32598290-6b404a42-c55f-11e7-9e4d-c82756b47f18.png)

---------------------------
Surprisingly some time it is able to retrieve all the chunks and also able to parse the response from influxdb server.

**Comment by nikunjdnp** [comment]
The same issue occurs for me when my node application is trying to get 1-year data from InfluxDb.

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
   at /root/influx-pull-data/node_modules/influx/lib/src/pool.js:160:69
   at <anonymous>
   at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by nikunjdnp** [comment]
The same issue occurs for me when my node application is trying to get 1-year data from InfluxDb.

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
   at /root/influx-pull-data/node_modules/influx/lib/src/pool.js:160:69
   at <anonymous>
   at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by srinivasrk** [comment]
Yes, similar problem. Using `queryRaw()` also gives same error.

**Comment by bencevans** [comment]
I bumped into this issue a little while ago and investigated but got side tracked. The following query worked for me:

```js
await influx.query('SELECT * FROM boat_battery WHERE time > ' + (((new Date()).valueOf() - 10 * 60 * 1000) * 1000000))
```

Does your query work when using the influx command line client?

**Comment by srinivasrk** [comment]
@bencevans Yes I can curl to the influx API to get the query, the output is a very long json which takes almost couple of minutes to print out to screen.
