### ISSUE TITLE
pool_1.Pool is not a constructor (Are my imports broken?)

### ISSUE THREAD

**Issue by gordeevbr** [node-influx/node-influx#305]
I'm using influx@5.0.7 npm package, but this can be reproduced with influx@next (5.0.0-alpha.4) also.
I am using typescript and webpack in my project.

I am importing InfluxDB client as 
`import {InfluxDB} from "influx";` 
in my source code and using it as 
`const InfluxInstance = new InfluxDB({...})`. 

I get the following error when I open compiled project in the browser:

`Uncaught TypeError: pool_1.Pool is not a constructor
    at new InfluxDB (index.js:211)
    at Object.662 (Influx.ts:13)`

The second line of stacktrace is my source code where I'm using the constructor.

When I open node-influx source code, I see that the Pool prototype is being exported as
`exports.Pool = Pool;`
But then it is imported as
`var pool_1 = require('./pool');`
I am not sure my webpack instance is interpreting this as intended. Do I need some special setup in my webpack config to get this to work?
If this code is working for you, could you please provide minimal webpack config?

Steps to reproduce:
1)Install via NPM into project with webpack and typescript.
2)Require in ".ts" file as mentioned above.
3)Bundle and launch in browser.

Webpack configuration: [webpack.conf.txt](https://github.com/node-influx/node-influx/files/1499602/webpack.conf.txt)

Thanks in advance.

**Comment by bencevans** [comment]
Should be fixed in the current release `5.1.0`:

```
$ ts-node
> import {InfluxDB} from "influx";
{}
> const InfluxInstance = new InfluxDB({})
undefined
> InfluxInstance
InfluxDB {
  _schema: [Object: null prototype] {},
  _pool:
   Pool {
     _options:
      { backoff: [ExponentialBackoff],
        maxRetries: 2,
        requestTimeout: 30000 },
     _index: 0,
     _hostsAvailable: Set { [Host] },
     _hostsDisabled: Set {},
     _timeout: 30000 },
  _options:
   { database: null,
     hosts: [ [Object] ],
     password: 'root',
     pool: undefined,
     schema: [],
     username: 'root' } }
> 
```
