### ISSUE TITLE
Bind parameters support

### ISSUE THREAD

**Issue by Cherry** [node-influx/node-influx#312]
It's possible that I'm simply missing it in the documentation, but it doesn't appear as if there is any support for bind parameters in this client.

Could this be added?
https://docs.influxdata.com/influxdb/v1.4/tools/api/#bind-parameters

**Comment by AnderbergE** [comment]
@Cherry Did you ever find any way to do this?
Without it user input basically makes node-influx unusable when a little Bobby Tables comes around.

**Comment by Cherry** [comment]
@AnderbergE Nope. We just had to be very careful about the data we were using. I'd definitely still love to see this feature supported though.

**Comment by AnderbergE** [comment]
I kind of thought so, so instead I implemented a solution where I escape all the input based on where in the query it is and feeding that into squel to build the query. It's not particularly pretty, but not that awful either, I am a bit unsure whether I've been able to cover all my bases though...
https://node-influx.github.io/variable/index.html#static-variable-escape
https://hiddentao.com/squel/

**Comment by Cherry** [comment]
This probably shouldn't be closed. Bind params support would still be great to see, and would bring this module closer to feature parity with the python client.

**Comment by bencevans** [comment]
A PR adding this functionality is very welcome however I don't currently have any need for this personally so shall not be a priority.

**Comment by Cherry** [comment]
Just adding a comment to prevent the stale bot from closing this. I feel like the bot should probably ignore certain labels like "help wanted" rather than just outright closing issues.

**Comment by dfliess** [comment]
has somebody worked on this ?

**Comment by bencevans** [comment]
@dfliess Fraid not, but a PR very welcome. Have updated the stale-bot to ignore 'help wanted' labelled issues. Thanks for the idea @Cherry.

**Comment by frezik** [comment]
Added placeholder support. Updated the docs to use placeholders, which I feel is an important thing to show so people get used to using them as much as possible.
