### ISSUE TITLE
InfluxDB connection over https

### ISSUE THREAD

**Issue by thorseye** [node-influx/node-influx#314]
It's unclear in the documentation on how to connect to an InfluxDB server, served over `https`. 

From what I understand, this configuration works: 

```js
{
  host: 'my-influxdb-instance.com',
  port: 443,
  protocol: 'https'
}
```

What I would have expected to work: 

```js
{
  host: 'https://my-influxdb-instance.com'
}
```

The above example does not work since you may not include protocol in the `host` property. Also, the `port` property should be optional.

Preferably, both variants should be accepted as valid configurations.

**Comment by NateZimmer** [comment]
Tricked me up to... thanks for the issue heh. I didn't spot protocol in the reference till you pointed it out

**Comment by konstantinblaesi** [comment]
what you provided is not a host, but a URL but afaik this library doesn't support `url` as an option?
