### ISSUE TITLE
Importing error classes not working according to doc

### ISSUE THREAD

**Issue by Radu94** [node-influx/node-influx#319]
I can't  require the proper error classes  from The influx lib. It only works for
[ResultError](https://node-influx.github.io/class/src/results.js~ResultError.html),  it fails for [RequestError](https://node-influx.github.io/class/src/pool.js~RequestError.html) and [ServiceNotAvailableError](https://node-influx.github.io/class/src/pool.js~ServiceNotAvailableError.html).

Snippet  illustrating my issue:
```javascript
const Influx = require('influx');

const ResultError = Influx.ResultError;
const RequestError = Influx.RequestError;
const ServiceNotAvailableError = Influx.ServiceNotAvailableError;
```

Influx version: 5.0.7
Node version: v8.9.1
OS: Windows 7

Did anyone else have similar problems ? If this is indeed a bug, i would be happy to help with a PR.
Thank you.

**Comment by TWAHRY** [comment]
I am having the same problem! my code doesn't execute the `const Influx = require('influx');` command! did you solve it?

**Comment by Radu94** [comment]
> I am having the same problem! my code doesn't execute the `const Influx = require('influx');` command! did you solve it?
I don't think the two are related, i could require it just fine :)

**Comment by bencevans** [comment]
@TWAHRY you must be using nodejs and have installed the module `npm install influx`. Or if using in a web environment then must be using a web bundler that supports npm modules.

**Comment by bencevans** [comment]
I can confirm @Radu94's issue:

```js
> const Influx = require('influx');
undefined
> Influx
{ Expression: [Function: Expression],
  Measurement: [Function: Measurement],
  parseMeasurement: [Function: parseMeasurement],
  parseWhere: [Function: parseWhere],
  FieldType:
   { '0': 'FLOAT',
     '1': 'INTEGER',
     '2': 'STRING',
     '3': 'BOOLEAN',
     FLOAT: 0,
     INTEGER: 1,
     STRING: 2,
     BOOLEAN: 3 },
  Precision:
   { Hours: 'h',
     Microseconds: 'u',
     Milliseconds: 'ms',
     Minutes: 'm',
     Nanoseconds: 'n',
     Seconds: 's' },
  Raw: [Function: Raw],
  escape:
   { measurement: [Function: bound escape],
     quoted: [Function: bound escape],
     stringLit: [Function: bound escape],
     tag: [Function: bound escape] },
  toNanoDate: [Function: toNanoDate],
  ResultError: [Function: ResultError],
  InfluxDB: [Function: InfluxDB] }
> const ResultError = Influx.ResultError;
undefined
> ResultError
[Function: ResultError]
> const RequestError = Influx.RequestError;
undefined
> RequestError
undefined
> const ServiceNotAvailableError = Influx.ServiceNotAvailableError
undefined
> ServiceNotAvailableError
undefined
> 
```

**Comment by bencevans** [comment]
The Errors need to be propagated up to the main domain for requirment such as your example @Radu94.

In the meantime they are exported from the pool module and can be imported with:

```js
require('influx/lib/src/pool').RequestError
require('influx/lib/src/pool').ServiceNotAvailableError
```

**Comment by Radu94** [comment]
@bencevans Thanks for taking the time to look into this :)
