### ISSUE TITLE
Custom URL / Nginx Support

### ISSUE THREAD

**Issue by NateZimmer** [node-influx/node-influx#324]
Perhaps i'm doing some thing wrong but this library does not appear to connect to `host` URL provided. 
E.g. if influx is bound to a URL such as the following:  **https://myDomain.com/aString/** , this library instead connects to **myDomain.com** and ignores the **/aString/** portion of the URL. 

This prevents the use of this library on servers using software like Nginx that forward requests via proxy by parsing the incoming URL

**Comment by cxcorp** [comment]
Could this issue be re-opened, please?

I've got a test case in this repo if you wish to see the issue in action: https://github.com/cxcorp/node-influx-subpath-case
