### ISSUE TITLE
Fix NPM Readme.

### ISSUE THREAD

**Issue by MicahZoltu** [node-influx/node-influx#329]
The top of https://www.npmjs.com/package/influx says to `npm install influx@next`.  Following these instructions results in getting a version that is 2 years out of date!

**Comment by bencevans** [comment]
Thanks for letting us know @MicahZoltu. The npm Readme will be updated on our next release which is being tracked as a separate issue at #327. Before we release we'd like to make Travis happy and upgrade some dependencies. Closing this as I consider it tracked as part of #327.
