### ISSUE TITLE
Getting a 401 Unauthorized Error

### ISSUE THREAD

**Issue by michael-iglesias** [node-influx/node-influx#330]
Hello,

When I make a CURL request to my telegraf instance the measurement I'm writing to successfully resolves. Also, when I construct an HTTP request using any nodejs HTTP library it works as well. Unfortunately, when I use the `influx` package I continue getting a 401 UnAuthorized error. I've tried making the constructor call using a connection URL as well as the IClusterConfig object with no luck. I've provided redacted code snippets below. Any help would be greatly appreciated!

CURL (WORKS):
`curl -i -XPOST 'http://<username>:<password>@<ip_address>:8186/write?db=dbname'
--data-binary 'cpu_load_short,host=server01,region=us-west value=0.64 1434055562000000000'`

Following code snippet (WORKS):
```
const request = require('request');

const options = { 
  method: 'POST',
  url: 'http://<username>:<password>@<ip_address>:8186/write?db=dbname,
  body: 'cpu_load_long,host=server01,region=us-west value=0.799 1434056562000000000'
};

request(options, function (error, response, body) {
    console.log(error);
    console.log(response.statusCode);
    console.log(body);
  if (error) throw new Error(error);

});
```

Influx Package (NOT working):
```
const influx = require("influx")

const i = new influx.InfluxDB("http://<username>:<password>@<ip>:8186/dbname")

i.writePoints([{
    timestamp: new Date(),
    tags: { foo: 'bar' },
    measurement: `foobar`,
    fields: { count: 1 } }
  ]).catch((err) => { console.error(err) })
```

**Comment by yellowiscool** [comment]
I have the same issue with InfluxDB `1.6.1` and `5.0.7`.

**Comment by bencevans** [comment]
node-influx doesn't currently support using a url, instead you have to provide host, database etc. documented at https://node-influx.github.io/typedef/index.html#static-typedef-ISingleHostConfig. A PR adding url handling would be welcome.

e.g.

```js
const influx = new Influx.InfluxDB({
 host: 'localhost',
 database: 'express_response_db'
})
```
