### ISSUE TITLE
Getting data from multiple measurements

### ISSUE THREAD

**Issue by utkarshns** [node-influx/node-influx#333]
I am trying to get data from multiple measurements like this:

_select * from EFC106,EFC107 where sensor = 'TRIP' AND time < 1537776229000000000 AND time > 1537602657000000000_

Expected Response:
name: EFC106
time                del sensor value
----                --- ------ -----
1537623403000000000 0   TRIP   0
1537623479000000000 0   TRIP   1
1537624320000000000 0   TRIP   0
1537624409000000000 0   TRIP   1
1537624754000000000 0   TRIP   0
1537625884000000000 0   TRIP   1
1537625892000000000 0   TRIP   0
1537625923000000000 0   TRIP   1
1537625934000000000 0   TRIP   0
name: EFC107
time                del sensor value
----                --- ------ -----
1537771544000000000 0   TRIP   1
1537771813000000000 0   TRIP   0
1537772868000000000 0   TRIP   1
1537773766000000000 0   TRIP   0
1537774403000000000 0   TRIP   1
1537775302000000000 0   TRIP   0
1537775331000000000 0   TRIP   1

But the actual response doesn't contain any names of the measurements.

**Comment by srinivasrk** [comment]
can you do this and show the output : 

```
curl -G http://<serverip>:8086/query --data-urlencode "pretty=true" --data-urlencode db=<dbname> --data-urlencode "q=select * from <measure1>,<measure2> limit 1"
```

**Comment by utkarshns** [comment]
Yeah, this works. I get the name tag too in the JSON. Replying from my
phone. Will send the JSON in some time.
