### ISSUE TITLE
Suggestion: use debug for logging

### ISSUE THREAD

**Issue by bertolo1988** [node-influx/node-influx#342]
I suggest you use [debug](https://www.npmjs.com/package/debug) as an internal logger. Quite useful to debug problems and it is quite a standard for node packages.

**Comment by bencevans** [comment]
Thanks for the suggestion @bertolo1988, i'm aware of the `debug` module and may well be useful in the future. Although another option is to use an over writable logger function and allow users / devs to bring their own to the mix when we provide log output. #229 may be an issue worth following or assisting in contributing to.
