### ISSUE TITLE
Error: Shard is disabled

### ISSUE THREAD

**Issue by robertsLando** [node-influx/node-influx#344]
I'm getting this error `Error: Error from InfluxDB: shard is disabled`

While running this command (copy all values from one db to another): 

`SELECT * INTO mydb.autogen.:MEASUREMENT FROM mydb_bak.autogen./.*/ GROUP BY *`

This only happens when using influx, everything works fine when running this command via InfluxDB shell

**Comment by bencevans** [comment]
Hi @robertsLando, were you able to identify a solution or find the cause?

**Comment by robertsLando** [comment]
I have hit this issue when trying to restore my db, the solution was to add a timeout after the restore about 1 sec before run other operations, I think that the shard is disabled and is not immediatly released for some reasons
