### ISSUE TITLE
Make influx errors easier to identify

### ISSUE THREAD

**Issue by broofa** [node-influx/node-influx#346]
Currently the only way to reliably identify an Influx error object is via code such as:
```
const {ResultError, ServiceNotAvailableError, RequestError} = require('influx');

if (err instanceof ResultError ||
    err instanceof ServiceNotAvailableError ||
    err instanceof RequestError) {
  // etc...
}
```
This is overly verbose, and also mandates an explicit dependency on `influx`, which can be awkward where generic error-handling/logging code is concerned.  It would be helpful if these errors had an `isInfluxError = true` property, to enable a simple test such as:
```
if (err.isInfluxError) {
  // etc...
}
```

**Comment by bencevans** [comment]
Sounds like a good idea to me. PR welcome :smile_cat:
