### ISSUE TITLE
TimeError

### ISSUE THREAD

**Issue by cdnblvck** [node-influx/node-influx#347]
Hi, i'm using influx(version: 1.6.3)  and when i try to get data on period exceed 15 days i have an error on the datetime. 
My request : `select * from "data_measurements" where (time>1547103386000 and time < 1551703790000)`
lastTimestamp return with node-influx :1547404546414
lastTimestamp i get with influx console : 1551703789672

**Comment by bencevans** [comment]
@cdnblvck please could you provide a test we can use in order to try and replicate your issue?
