### ISSUE TITLE
InfluxDB backup and restore on npm

### ISSUE THREAD

**Issue by robertsLando** [node-influx/node-influx#348]
Hi, I have just published the first version of `influx-backup` npm module. Any feedback is welcome. 
Check it here --> https://www.npmjs.com/package/influx-backup

**Comment by bencevans** [comment]
We're here! Just need the test suite to pass before we release...

**Comment by sresam89** [comment]
Was this feature merged?

**Comment by bencevans** [comment]
Hmm, confused by my last comment 🤔 @sresam89 `influx-backup` is a separate project from `node-influx`. Repo's at https://github.com/robertsLando/node-influxdb-backup
