### ISSUE TITLE
"UnhandledPromiseRejectionWarning: Error: write EPIPE" when mass-inserting data

### ISSUE THREAD

**Issue by DerNamenlose** [node-influx/node-influx#350]
I'm a total newbie to working with InfluxDB and currently try to set up a test system for some performance tests for my specific use case. For that I'm trying to set up a database with test values to query later. However, I fail at the first step already.

My dummy data generator looks like this:
```javascript
const influx = require("influx");

(async () => {
    console.log("Connecting to database");
    let db =new influx.InfluxDB({
        host: 'localhost',
        database: 'test',
        schema: [
            {
                measurement: 'values',
                fields: {
                    value: influx.FieldType.FLOAT
                },
                tags: [
                    'tag'
                ]
            }
        ]
    }); 

    const dbNames = await db.getDatabaseNames();
    if (!dbNames.includes('test'))
    {
        console.log("Creating database");
        await db.createDatabase('test');
    }

    let batch = []
    for (let i = 1; i <= 1000000; i++)
    {
        batch.push({
            timestamp: new Date(2019, 2, 19, 0, 0, 0, 0).getTime()+i*1000,
            measurement: 'values',
            tags: { tag: 'tag1' },
            fields: { value : Math.random()*90 }
        });
    
        if (i % 10000 == 0) 
        {
            console.log(`Finished ${i} elements`);
            await db.writePoints(batch)
        }
    }
})()
.catch(error => {
    console.log(`Failed: ${error}`);
})
```

Nothing fancy, just inserting random values with the same tag and increasing timestamps. This works to around 470000 items inserted, when it finally fails with `Failed: Error: A 413 Request Entity Too Large error occurred: {"error":"Request Entity Too Large"}`

I'm testing against the standard docker container installation. The failed request is logged on the console as

```
[httpd] 172.17.0.1 - root [19/Mar/2019:21:26:29 +0000] "POST /write?db=test&p=%5BREDACTED%5D&precision=n&rp=&u=root HTTP/1.1" 204 0 "-" "-" a8c6d509-4a8d-11e9-80a0-0242ac110002 1147352
ts=2019-03-19T21:26:31.272839Z lvl=info msg="Cache snapshot (start)" log_id=0EHwrWLl000 engine=tsm1 trace_id=0EHyQ_Q0000 op_name=tsm1_cache_snapshot op_event=start
[httpd] 172.17.0.1 - root [19/Mar/2019:21:26:31 +0000] "POST /write?db=test&p=%5BREDACTED%5D&precision=n&rp=&u=root HTTP/1.1" 413 37 "-" "-" aa48c0a6-4a8d-11e9-80a1-0242ac110002 1881
ts=2019-03-19T21:26:32.136674Z lvl=info msg="Snapshot for path written" log_id=0EHwrWLl000 engine=tsm1 trace_id=0EHyQ_Q0000 op_name=tsm1_cache_snapshot path=/var/lib/influxdb/data/test/autogen/7 duration=863.852ms
ts=2019-03-19T21:26:32.136700Z lvl=info msg="Cache snapshot (end)" log_id=0EHwrWLl000 engine=tsm1 trace_id=0EHyQ_Q0000 op_name=tsm1_cache_snapshot op_event=end op_elapsed=863.876ms
```
(see the 413 request in the middle).

Any idea what I might do wrong? Is this a bug in node-influx or InfluxDB? I've tried recycling the client instance after a few writes, but that didn't change anything.

InfluxDB version: version=1.7.4 branch=1.7 commit=ef77e72f435b71b1ad6da7d6a6a4c4a262439379 running in the standard influxdb Docker container
node-influx: 5.0.7

Thanks in advance for any help possible.

**Comment by kMeillet** [comment]
https://github.com/influxdata/influxdb/issues/12731

1) Put **{ precision: 'ms' }** as second argument of write function (because you use milliseconds timestamp from Date object).

2), You should be aware that InfluxDB limit the size of write payload. https://docs.influxdata.com/influxdb/v1.7/administration/config/

3) Set INFLUXDB_HTTP_MAX_BODY_SIZE to zero ---> Avoid 413 HTTP response.

**Comment by DerNamenlose** [comment]
Thanks. Setting the precision to milliseconds didn't actually change a thing, but I guess that wasn't the goal anyway. Setting INFLUXDB_HTTP_MAX_BODY_SIZE actually let me finish the import job, but the resident size of the influxdb process kept on increasing throughout the import and didn't shrink afterwards. I guess I'll have to go through the config options again to see how this is supposed to be controlled.
