### ISSUE TITLE
Resampling

### ISSUE THREAD

**Issue by abeikverdi** [node-influx/node-influx#351]
Why isn't there any resampling option in createContinuousQuery in index.js? I see in the type script file that the forth option passes resampling however this functionality is missing in the javascript file. Is there a specific reason for this? We highly require this functionality. I can open a PR for this.

**Comment by abeikverdi** [comment]
I noticed its in the latest version in 5.0.8 however I am not able to install the github repo through npm.

**Comment by bencevans** [comment]
Sorry about that @abeikverdi. There will be a release soon, however in the meantime you should be able to install the GitHub repo through npm with...

    $ npm i github:node-influx/node-influx
