### ISSUE TITLE
Handle chunked query responses

### ISSUE THREAD

**Issue by klyngbaek** [node-influx/node-influx#39]
It would be nice to make a query and handle chunked responses.
##

**Comment by AdoHe** [comment]
@bencevans I thinks this need to be done with the `request` module....

**Comment by shaunwarman** [comment]
Any update here? Seems like large queries/responses will kill the influx process.

**Comment by shaunwarman** [comment]
After some local testing, it looks like influx doesn't handle chunking very well when the response is extremely large. It seems the best approach is to split large time series into multiple queries.

**Comment by connor4312** [comment]
Adding support for this in the 5.0.0 branch today

**Comment by connor4312** [comment]
I'm moving this off to 5.1.0 awaiting Influx 1.1, which will support [csv encoded responses](https://github.com/influxdata/influxdb/pull/7099). This will let us start streaming results as they _start_ come back from Influx without having to demarshal the entire JSON response. End goal is that chunked responses will simply appear as an EventEmitter stream to the consumer.

```
influx.chunkQuery('select * from perf')
  .on('series', series => console.log('Start of series', series))
  .on('row', row => console.log('got a row', row))
  .on('end', () => process.exit(0))
```

**Comment by MattJustMatt** [comment]
@connor4312 yo! 1.1 is out now. Any update on this?

**Comment by bcatalin** [comment]
I am also interested in this or in a method to get large amount of data. I have like 800000 measurements per day and the system is up for more then 90 days. I need a way to get data and plot them using amCharts, but of course that I can not get this volume in one call.

**Comment by lemonov** [comment]
I can see that this topic is stale but are chunked queries planned for any release or the topic is dropped?

**Comment by bencevans** [comment]
If there's someone willing to contribute this feature then it will be gladly accepted! However I don't have any need for developing this personally and do not have the resources to allocate to it otherwise.
