### ISSUE TITLE
writePoints fails with `BigInt` values

### ISSUE THREAD

**Issue by brahma-dev** [node-influx/node-influx#423]
## Expected Behavior
Write value to database

## Actual Behavior
Throws error for calling `Math.floor` @ https://github.com/node-influx/node-influx/blob/master/src/schema.ts#L81

**Comment by bencevans** [comment]
Hi @brahma-dev 

Please can you provide a code sample as our tests are all passing and so unsure how we're able to replicate the error you're getting.

Cheers

Ben

**Comment by brahma-dev** [comment]
Something like this. It's because the builtin `Math` functions do not work on `BigInt` yet.
```js
const influxclient = new Influx.InfluxDB({
    // or single-host configuration
    host: "127.0.0.1",
    database: "somedb",
    schema: [{
        measurement: "data",
        fields: {
            value: Influx.FieldType.INTEGER
        },
        tags: ["tag"]
    }]
});
influxclient.writePoints([{
    measurement: "data",
    tags: {
        tag: "something",
    },
    fields: {
        value: BigInt("22222222")
    },
    timestamp: timestamp
}])
```

I fixed it here. https://github.com/brahma-dev/node-influx/blob/da20b515905ab88f4ff655acf2eeb551267b8f7b/src/schema.ts#L81
That only solves it for pushing data.
