### ISSUE TITLE
field type conflict

### ISSUE THREAD

**Issue by mburger81** [node-influx/node-influx#436]
## Expected Behavior
Ability to write points to remote influxdb

## Actual Behavior
On writing a simple measurement like this
```
[ { measurement: 'orma_ambiance',
    tags: { sensor_id: '70:b3:d5:47:50:10:03:d9', endpoint_id: 16 },
    fields:
     { temperature: 25.16, humidity: 25, co2: 732, presence: 2990 },
    timestamp: 2019-05-15T20:01:14.000Z } ]
```

we get this error:
`{ Error: A 400 Bad Request error occurred: {"error":"partial write: field type conflict: input field \"co2\" on measurement \"orma_ambiance\" is type float, already exists as type integer dropped=1"}`

But the problem is as you can see co2 field is 732 which is already an integer number.
It seems client use ALWAYS float instead of integer on writing points.

Some ideas?

## Specifications

  - Version: 5.4.0
  - Platform: macOS 10.14.5
  - Subsystem:

**Comment by bencevans** [comment]
Hmm in your schema is humidity also set as integer?

**Comment by bencevans** [comment]
One way around it would be to update your schema to store co2 as float rather than integer.

**Comment by mburger81** [comment]
Yes only Temperatur is float. The question is why client sends the other  fields like CO2 and and presence as float value? Can we debug this? Can we see how the push is done?

**Comment by bencevans** [comment]
Have you setup your schema in node-influx... https://node-influx.github.io/typedef/index.html#static-typedef-ISchemaOptions. node-influx needs to be aware of the specific types else if it's not defined it may be defaulting to Float.

**Comment by bencevans** [comment]
Schema options are passed to node-influx likes so:

```js
const influx = new Influx.InfluxDB({
  host: 'localhost',
  database: 'express_response_db',
  schema: [
    {
      measurement: 'response_times',
      fields: {
        path: Influx.FieldType.STRING,
        duration: Influx.FieldType.INTEGER
      },
      tags: [
        'host'
      ]
    }
  ]
})
```

> https://node-influx.github.io/manual/tutorial.html#express-response-times-example

**Comment by mburger81** [comment]
No we didn't. So that's the reason probably. 
The strange thing is that we have this behavior only from a while. We used the same scripts a few times before without this type of issue. 
Does there amythung changed in the last releases in the last 8 month?

**Comment by bencevans** [comment]
2de6675e58a9ef53f7d08ec91054444656483f7f is somewhat related but not sure it'd trigger your issue. A summarised changelog can be found at https://github.com/node-influx/node-influx/releases or more detail at https://github.com/node-influx/node-influx/commits/master

**Comment by mburger81** [comment]
Okay, that resolved me our problem.

Not sure why this is was working before. We test also first 5.0.0 version, but also there we have the problem. So not sure in which condition we was before.

But setting schema resolves me the problem!!! I didn't knew this.
Thx a lot!
