### ISSUE TITLE
"TypeError: Cannot read property '0' of undefined"

### ISSUE THREAD

**Issue by farishsn** [node-influx/node-influx#444]
Please  shed some light on this .

below is the function on node-red

msg.payload = [
    {
        measurement: "infy",
        fields: {
             BID: msg.payload1[0], 
        
            OFFER: msg.payload2[0],
             
        },
        tags:{
            location:"BSE", 
         
        },
        timestamp: new Date()
    },
    
];
return msg;

**Comment by bencevans** [comment]
Hi @farishsn 

Please could you be more descriptive as to what you're wanting to know?

If it's specific to the `node-red-contrib-influxdb` module you may be better off opening an issue on that project at https://github.com/mblackstock/node-red-contrib-influxdb

**Comment by farishsn** [comment]
Hi @bencevans 

I'm very beginner to Node-red and influx db. I was trying to return  values from two functions say X & Y msg.payload1, msg.payload2  on to a different function Z which is below, so i can  send these values to influx db with measurement "infy" and fields " BID & OFFER". So when i try to run both individually (ie,  X to Z or Y to Z )doesnot give any error. but when try to run like below (both X,Y  to > Z) gives error.
--------------------------------------------------------------------------------------------------------------
"TypeError: Cannot read property '0' of undefined" 
--------------------------------------------------------------------------------------------------------------
If this is not the right way, please tell me if there is another. :)
-------------------------------------------------------------------------------------------------------
![Flow](https://user-images.githubusercontent.com/53030866/61532481-8c9cd880-aa47-11e9-88f3-18d0082f6a83.JPG)
![X](https://user-images.githubusercontent.com/53030866/61532487-90c8f600-aa47-11e9-9e4d-853efb2031d9.JPG)
![Y](https://user-images.githubusercontent.com/53030866/61532489-9292b980-aa47-11e9-99f5-c47c7f5493b1.JPG)
![Z](https://user-images.githubusercontent.com/53030866/61532492-945c7d00-aa47-11e9-90b7-12a495187152.JPG)

**Comment by bencevans** [comment]
I'm not very familiar with node-red an how it passes information around. I don't think this is an issue with node-influx itself but how the data is transferred between your nodes in node-red and into your function.

Quickly skimming the README of https://github.com/mblackstock/node-red-contrib-influxdb I'm not sure there is payload1 and payload2 objects. I suggest opening an issue at https://github.com/mblackstock/node-red-contrib-influxdb/issues as that is the home for the node-red integration.

**Comment by farishsn** [comment]
Thank  you  ben @bencevans
