### ISSUE TITLE
Question: Finding out my query's id and terminating it through the driver

### ISSUE THREAD

**Issue by SamuelToh** [node-influx/node-influx#446]
Hi all,

Is there a way for the driver to tell me the query Id of my influxQL, after I have made the call?

My use case is that, my influxQL query might take a few seconds to run but I would like them to be to forcefully terminated if it is taking longer than 'n' seconds.

I have scanned through the documentations already but have not found a way forward.

The closest I can think of is to actually issue a "show queries" call with a filter where query = 'blah' and then use the "KILL" keyword to terminate it. 

Probably a nice feature for the driver to handle this for me.

**Comment by bencevans** [comment]
Sounds like a good enhancement
