### ISSUE TITLE
API to directly insert line protocol string

### ISSUE THREAD

**Issue by shantanoo-desai** [node-influx/node-influx#459]
## Expected Behavior
instead of `IPoints[]` Object is it actually possible to insert a line protocol string directly with `node-influx`?

e.g.

```
     const line = 'env,location=us-dallas temp=20.23,humid=34.3 1565552805'
     InfluxDB.writePoint(line).then(resp => )
```

## Actual Behavior
currently the API Documents do not mention direct insertion but only by splitting the information in `IPoints[]`. Or if there is a possibility I do not see any API documentation or Example for the same.

**Comment by bencevans** [comment]
Hi @shantanoo-desai you could use the pool to send manual requests bypassing the writePoints logic. I would suggest reading the [writePoints](https://github.com/node-influx/node-influx/blob/cae86ed54106afeaa89b2624e00c2aef34b64b69/src/index.ts#L1206-L1247) function and drilling down into the pool library from their to find which level of abstractions works best for you.
