### ISSUE TITLE
writePoints doesn't check against the FieldType 

### ISSUE THREAD

**Issue by 7hibault** [node-influx/node-influx#465]
Hi all,

I don't know if this is a bug, a feature request or a desired behaviour but I'll fill this in as a bug, I can edit later depending on the discussion.

## Expected Behavior

After creating a database using `new Influx.InfluxDB()` and specifying `FieldType.FLOAT` as a type for a field, inserting data with the wrong type should either result in an error or a cast.

## Actual Behavior

The data gets inserted with the wrong type. This is extremely annoying because my fields now have the wrong type (`string` instead of `float`) [that cannot be changed](https://docs.influxdata.com/influxdb/v1.7/troubleshooting/frequently-asked-questions/#can-i-change-a-field-s-data-type).

>  There is no way to cast a float or integer to a string or Boolean (or vice versa).

## Steps/Code to Reproduce the Problem

  1. Create a database

```
const influx = require('influx')
const influx = new Influx.InfluxDB({
  host: 'localhost',
  database: 'example_db',
  schema: [
    {
      measurement: 'example',
      fields: {
        floatField: Influx.FieldType.FLOAT             // FIELD DEFINED AS A FLOAT
      }
    }
  ]
})
influx.createDatabase('example_db');
```

2. Insert data using wrong types

```
    data = [];
    influx.writePoints([
      {
        measurement: 'example',
        fields: { 
          floatField: '100'                         // USING A STRING HERE
        },
      }
    ]).catch(err => {
      console.error(`Error saving data to InfluxDB! ${err.stack}`)
    })
```

3. Check the field keys

```
> show field keys
name: floatField
fieldKey fieldType
-------- ---------
floatField string
```

## Specifications

  - Version: 5.0.7
  - Platform: Windows
  - Subsystem:

**Comment by ZachHerridge** [comment]
I'm having a similar issue where inserting a String like '+1' into a String typed field results in 1.0 number type.
