### ISSUE TITLE
Uanble to write data to the DB

### ISSUE THREAD

**Issue by kedardahivale** [node-influx/node-influx#469]
## Expected Behavior
InfluxDB.witePoints() should write the date to the DB 

## Actual Behavior
Unable to write the data getting a error Below is the error:

_Error: A 400 Bad Request error occurred: {"error":"unable to parse 'NODE_DELETE,name=Waypoint_25,sectorReference=5ba4c104d638ec66e84086bf,_type=NODE,type=NODE,id=5d91f9415b3288779090d9e7,service=nodesrv __v=0,_capabilities.0._action=\"2\",_capabilities.0._id=\"5d91f94130fe6b77a0d852a8\",_capabilities.0.envelope.empty=true,_neighbours.empty=true,_occupado.empty=true,coordinates.geo.alt=0,coordinates.geo.lat=-0.00053,coordinates.geo.lng=0.000191,coordinates.id=null,coordinates.pose=0,coordinates.x=21.30171961451117,coordinates.xyz.x=21.30171961451117,coordinates.xyz.y=-58.97930198425131,coordinates.xyz.z=0,coordinates.y=-58.97930198425131,coordinates.z=0,depth=1,description=\"\",innerCollision=false,innerSecurityZone=0.3,optional.empty=true,outerCollision=false,outerSecurityZone=0.9,params.capacity=10,params.counter=0,useLocalSettings=false': invalid number"}__

## Steps/Code to Reproduce the Problem

  1.
  1.
  1.

```
const influx = require('influx')


// ...
```

## Specifications

  - Version:latest 
  - Platform: Ubuntu 18.04
  - Subsystem:

**Comment by bencevans** [comment]
Please could you provide us with a code snippet that this fails on?

**Comment by bencevans** [comment]
Closing due to missing requested information.
