### ISSUE TITLE
How to enable gzip compression in influx-client https interface

### ISSUE THREAD

**Issue by megastef** [node-influx/node-influx#479]
## Expected Behavior

An optional compression would be useful to reduce network traffic
HTTP/HTTPS connection should be compressed.
How can we pass http.agent options to influx client?  

## Actual Behavior

HTTP requests are not compressed 

## Steps/Code to Reproduce the Problem

- According to the source code body is not compressed
  https://github.com/node-influx/node-influx/blob/master/src/pool.ts#L419-L422

```
this.connectionOptions = {
    host: config.influx.host || apiUrl.hostname,
    port: Number(config.influx.port) || Number(apiUrl.port) || 443,
    database: config.influx.dbName || 'metrics',
    protocol: config.influx.protocol || apiUrl.protocol.replace(':', ''),
    // did not work: 
    // headers: {'Content-Encoding': 'gzip'}
    // did not work: 
    options: {
      headers: {'Content-Encoding': 'gzip'}
    }
  })
this.influx = new Influx.InfluxDB(this.connectionOptions)
// ...
```

## Specifications

  - Version: influx@5.5.1
  - Platform: Mac OS X
  - Subsystem:

**Comment by bencevans** [comment]
By providing an `options` object in the config block used to instantiate `InfluxDB` you're able to provide opts that are passed to the `http.request`, including an agent.

* https://node-influx.github.io/typedef/index.html#static-typedef-ISingleHostConfig
* https://nodejs.org/api/https.html#https_https_request_options_callback

```js
const Influx = require('influx');
const myAgent = ...

const influx = new Influx.InfluxDB({
 host: 'localhost',
 database: 'express_response_db',
 schema: [
   {
     measurement: 'response_times',
     fields: {
       path: Influx.FieldType.STRING,
       duration: Influx.FieldType.INTEGER
     },
     tags: [
       'host'
     ]
   }
 ],
 options: {
  agent: myAgent
 }
})
```
