### ISSUE TITLE
Influxdb v2.0.0 beta support

### ISSUE THREAD

**Issue by VijetaH** [node-influx/node-influx#483]
Any plans of supporting the latest verison of influxdb? https://v2.docs.influxdata.com/v2.0/api/

**Comment by Clan-Utility** [comment]
Any idea if we can use the current version to [send flux query](https://docs.influxdata.com/flux/v0.50/guides/executing-queries/#influxdb-api)?

**Comment by russorat** [comment]
@Clan-Utility take a look at https://github.com/influxdata/influxdb-client-js/ for that capability.

**Comment by bencevans** [comment]
There are no plans to support v2. As @russorat mentions Influx now have their [own JavaScript client](https://github.com/influxdata/influxdb-client-js/) and I recommend migrating over to using that in place of node-influx.
