### ISSUE TITLE
Dynamic query fomation 

### ISSUE THREAD

**Issue by Tatya-winchu** [node-influx/node-influx#485]
## Expected Behavior
 To able to make a dynamic query with multiple where condition.
Ex. SELECT * FROM "measurement" WHERE "Condition" = value AND time >= start date AND time >= end date

**Comment by bencevans** [comment]
Hi @Tatya-winchu 

This should already be covered with the following...

```js
  influx.query(`
    SELECT * FROM "measurement"
    WHERE "Condition" = value
    AND time >= start date AND time
  `).then(result => {
    res.json(result)
  }).catch(err => {
    res.status(500).send(err.stack)
  })
```

**Comment by Tatya-winchu** [comment]
@bencevans  Thanks for your response :) I have small query regarding use for builder.js to build a query. Is it possible to use builder.js to form a dynamic query?

**Comment by bencevans** [comment]
Check out https://node-influx.github.io/class/src/builder.js~Expression.html for documentation and the tests covering it provides examples too https://github.com/node-influx/node-influx/blob/master/test/unit/builder.test.ts

**Comment by Tatya-winchu** [comment]
@bencevans  
`  influx.query(`
    SELECT * FROM "measurement"
    WHERE "Condition" = value
    AND time >=  new Date(0).toISOString()
    AND time <=  new Date().toISOString
  `).then(result => {
    res.json(result)
  }).catch(err => {
    res.status(500).send(err.stack)
  })` this throws an error invalid time format?
