### ISSUE TITLE
Bad string generating by Expression

### ISSUE THREAD

**Issue by Zeruk** [node-influx/node-influx#486]
## Expected Behavior

Trying to escape some random input to break expression
```
exp = new Influx.Expression();
exp.tag('symbol').equals.value(`GAZP()\'`).toString() // **`"symbol" = 'GAZP()\\\''`**
```
And it should escape characters correctly

## Actual Behavior
But it doesn't escape them
```
exp = new Influx.Expression();
exp.tag('symbol').equals.value(`GAZP()\'`).toString() // **`"symbol" = 'GAZP()\\''`**
```

## Steps/Code to Reproduce the Problem
```
const influx = require('influx')
const exp = new influx.Expression();
exp.tag('symbol').equals.value(`GAZP()\'`).toString()
// ...
```

## Specifications

  - Version: 5.5.1
  - Platform: Darwin

**Comment by Zeruk** [comment]
More than that, it also allows SQL-injections:
```
exp.tag('symbol').equals.value(`GAZP()\' or 1=1 --`).toString()
```
Query with such "Where" clause will return all rows from measurement

**Comment by bencevans** [comment]
Hi @connor4312. Hope you're well! Did you get a chance to look into this? Cheers, Ben

**Comment by connor4312** [comment]
Not yet. Though I plan to use Influx again (for the first time in ages) for some home automation stuff, so I will probably be spending some time on this library again

**Comment by robertsLando** [comment]
@bencevans any news on this? it's introducing some high security risk
