### ISSUE TITLE
[bug] TCP streams are not closed

### ISSUE THREAD

**Issue by robertsLando** [node-influx/node-influx#501]
## Problem

I'm writing some test code using [tap](https://www.npmjs.com/package/tap) and I noticed that tests never ends and the problem is caused by leaked tcp streams that remains open. I was looking for a `close` method for influx instance but as it uses http requests it doesn't have it.

## Steps/Code to Reproduce the Problem

Simply init an influx db and use [leaked-handles](https://www.npmjs.com/package/leaked-handles) to see opened tcp streams

```js
const Influx = require('influx');
require('leaked-handles')

const influx = new Influx.InfluxDB({
 host: 'localhost',
 database: 'test'
})

const hosts = await influx.ping(5000)

console.log('Tcp streams are still opened here')

```

## Specifications

  - Version: 5.5.1
  - Platform: Linux

**Comment by bencevans** [comment]
Has #495 fixed this @robertsLando? If not a PR would be appreciated. I'm not really able to maintain this at the moment and would appreciate people up for maintaining to come forward.

**Comment by robertsLando** [comment]
Nope, just tried, it it hasn't been fixed. Now I will check the code

**Comment by robertsLando** [comment]
I'm not able to find the bug @bencevans . I believe that it's on `ping` method. The leaked handles output is:

```
tcp stream {
  fd: 28,
  readable: false,
  writable: true,
  address: {},
  serverAddr: null
}

tcp stream {
  fd: 32,
  readable: false,
  writable: true,
  address: {},
  serverAddr: null
}
```

So seems there are streams that remains opened after the ping call. I see there is `req.end()` so I don't understand why

**Comment by robertsLando** [comment]
@bencevans Have you ever think to use modules like [bent](https://github.com/mikeal/bent/tree/master/src) for requests and make all the codebase async/await?

**Comment by robertsLando** [comment]
I have found the problem, was not something related to this lib. Anyway take a look at my previous comment and let me know what you think about that
