### ISSUE TITLE
Verify Connection(exit code for Icinga2)

### ISSUE THREAD

**Issue by Peaky-Saqi** [node-influx/node-influx#508]
Hi,
I am new in a programming world, so my first task is:

to write a PowerShell code.
If data has been written in the database, with 0 error then OK otherwise Critical.
here is some info, how the script should work, and give us results.
curl.exe -G 'http://:8086/query?pretty=true?u=&p=' --data-urlencode "db=" --data-urlencode "q=SELECT value FROM test WHERE host='testhost'"
 OK – connection to the database is fine
 Critical – check database

OK:
PS C:> curl.exe -G 'http://:8086/query' --data-urlencode "db=" --data-urlencode "q=SELECT value FROM test WHERE host='testhost'"

{"results":[{"statement_id":0,"series":[{"name":"test","columns":["time","value"],"values":[["2015-06-11T20:46:02Z",1],["2020-07-08T12:03:46.888557154Z",1]]}]}]}

Critical:
PS C:> curl.exe -G 'http://:8086/query?pretty=true' --data-urlencode "db=" --data-urlencode "q=SELECT value FROM test WHERE host='testhost'"
curl: (7) Failed to connect to internal-monitoring-hist.tgwdev.internal port 8086: Connection refused

PS C:> curl.exe -G 'http://:8086/query?pretty=true' --data-urlencode "db=" --data-urlencode "q=SELECT value FROM test WHERE host='testhost'"
{
"results": [
{
"statement_id": 0,
"error": "database not found: sampledb"
}
]
}

Example for exit codes

Exitcodes für ps
if($PortTotal -le $warnPorts) {
Write-Output "Ports OK '$PortTotal' Ports are open"
Exit(0)
}
else {
Write-Output "Ports Critical '$PortTotal' Ports are open"
Exit(2)
}

Link for instruction:
https://docs.nsclient.org/howto/external_scripts/

If it is not clear, I will explain it again.

**Comment by bencevans** [comment]
Hi @Peaky-Saqi 

This issue board is for the node-influx package. An InfluxDB client for JavaScript so I'm afraid not quite the right place for your question. I personally have very little to do with PowerShell. I'd suggest trying on the InfluxData [Community](https://community.influxdata.com/) or [Slack](https://influxdata.com/slack).

Best of luck on your programming adventures!
