### ISSUE TITLE
latest release breaks writing any non-string value

### ISSUE THREAD

**Issue by contra** [node-influx/node-influx#516]
The latest release to fix the SQL injection broke existing usage on a non-major release. Commit: https://github.com/node-influx/node-influx/commit/dcc2e7e9564e0303a771a1402ac59a46d6a0a082

Looking at the code briefly not sure why this would break it, but we have untouched code that works fine before 5.5.3 and produces this consistently after updating.

## Code to Reproduce the Problem

```
const influx = require('influx')

// set up any connection, doesnt matter

db.writePoints([
  {
    measurement: 'requests',
    tags: {
      primary: true,
      endpoint: 'insight.validate',
      keyUserId: undefined,
      key: undefined
    },
    fields: { path: '/insights/validate', errored: false, statusCode: 200 }
  }
])
```

throws

```
TypeError: val.replace is not a function
    at Escaper.escape (/Users/contra/Projects/staeco/services/api/node_modules/influx/lib/src/grammar/escape.js:56:19)
    at /Users/contra/Projects/staeco/services/api/node_modules/influx/lib/src/index.js:846:40
    at Array.forEach (<anonymous>)
    at InfluxDB.writePoints (/Users/contra/Projects/staeco/services/api/node_modules/influx/lib/src/index.js:833:16)
```

## Specifications

- Version: 5.5.3, 5.6.0

**Comment by svedbg** [comment]
Following change should fix the issue: https://github.com/node-influx/node-influx/pull/517/commits/d0ca62623bb1d86652ea47db86601ba303fbcbd5
