### ISSUE TITLE
Proper response encoding to support unicode characters

### ISSUE THREAD

**Issue by par6n** [node-influx/node-influx#521]
## Expected Behavior
This package is using Node.js internal `http` module to transmit request and receive response from InfluxDB HTTP server. Since the response is an object of type `Http.IncomingMessage`, `data` event is emitted multiple times, each time containing a part of the whole response.

This should correctly handle Unicode characters, if they're in the middle of two chunks, e.g:
```
// chunk 1
{"response":"سلام، این یک م

// chunk 2
تن فارسی است"}
```

## Actual Behavior
Seems like Node.js (tested against 10.x and 12.x) doesn't handle Unicode characters correctly and Unicode characters would get corrupt and there's a chance that the whole JSON response gets corrupt.

## Steps/Code to Reproduce the Problem
Reproducing it depends on environmental conditions like your kernel configuration, Linux distribution and Node.js version. I couldn't refactor this on my own Ubuntu Desktop 20.04, but the problem was recurring on CentOS 6 machines.

## Solution
The solution I found was quite easy. I added the below line to `stream()` method in [src/pool.ts:380](https://github.com/node-influx/node-influx/blob/master/src/pool.ts#L380):
```
res.setEncoding('utf8');
```
and the problem was solved! I've noticed that the same solution is implied in [official Node.js documentation](https://nodejs.org/api/http.html#http_http_get_url_options_callback), see that they're using string manipulation as well.

## Specifications

- Version: 5.5
- Platform: Linux (both client and InfluxDB server)

**Comment by bencevans** [comment]
Cool, thanks for the clear report! Would you be up for submitting a PR with the mentioned solution and a test?

**Comment by par6n** [comment]
Yup! I will submit a PR soon with a test.
