### ISSUE TITLE
Suggestion: show stats and show diagnostics

### ISSUE THREAD

**Issue by rnd-debug** [node-influx/node-influx#529]
Influx CLI has two commands that return some runtime stats of the DB :  [`show stats` and `show diagnostics`](https://docs.influxdata.com/platform/monitoring/influxdata-platform/tools/)
How about providing similar functions in **node-influx**? Something like `influx.showStats` maybe, that will return an object:
```
{
"runtime": {"Alloc": 42, "Frees":4242, ...},
"queryExecutor": {"queriesActive": 1, ...}
}
```
Basically it will be a wrapper around `influx.query("show stats")`.
The final idea of this is for the user to be able to JS-monitor influx stats on a regular basis (f.e. every hour) and empty the DB if it is getting "too voracious".

**Comment by rnd-debug** [comment]
Any news?

**Comment by bencevans** [comment]
As this can be achieved fairly simply just using the query function I'm hesitant to add further functionality but open to others opinions on the matter.
