### ISSUE TITLE
unable to send metrics to InfluxDB

### ISSUE THREAD

**Issue by eliw00d** [node-influx/node-influx#531]
## Expected Behavior

Able to send metrics to InfluxDB on default localhost:8086 with node-influx.

## Actual Behavior

```
unable to send metrics to InfluxDB. err=Post http://localhost:8086/write?consistency=&db=&precision=ns&rp=: dial tcp w.x.y.z:8086: connect: connection refused
```

Where w.x.y.z is actually a different host than localhost

## Steps/Code to Reproduce the Problem

If we POST with [axios](https://www.npmjs.com/package/axios) to localhost:8086 it just works. Why doesn't it work with node-influx? Is there additional configuration we need?

## Specifications

- Version: 5.6.3
- Platform: Kubernetes-like
- Subsystem: Linux

**Comment by bencevans** [comment]
Has `w.x.y.z` been changed to redact something? This seems very odd if the domain from the URL is localhost :thinking:

**Comment by eliw00d** [comment]
Yeah, it was just a private IP address that is a separate host.
