### ISSUE TITLE
Incorrect encoding when using placeholders / bind parameters

### ISSUE THREAD

**Issue by nordenmark** [node-influx/node-influx#539]
The `placeholders` is not correctly encoded in the request to the influx instance (see https://docs.influxdata.com/influxdb/v1.8/tools/api/#bind-parameters for expected encoding)
 
Using the following query: 

```
influx.query(
  'select * from response_times where host = $host', 
  { 
    placeholders: { host: 'example' } 
  }
);
```

## Expected Behavior

Query parameter `params` should be `params={ host: 'example' }`

## Actual Behavior

Query parameter `params` is  empty (`params=`)

## Details

When the path is built up in `pool.ts` on line 363, `querystring.stringify(options.query);` is used, and it does not support nested objects.  

In a scenario where `options.query` looks like the following:

```
const options = {
  query: {
    p: 'pwd',
    u: 'user',
    params: { host: 'example' }
  }
};

querystring.stringify(options.query) === 'p=pwd&u=user&params='
```

## Proposed solution

We need to call `JSON.stringify` on the `placeholders` object before we use `querystring.stringify()`

## Specifications

- Version: 5.6.3
- Platform: OS X

**Comment by iwarp** [comment]
I ran in to the same problem when using multiple parameters, I've encoded that before i execute the query. It would be good to fix so i can remove the ts-ignore

`        
       const placeholders = {
             param1 = 'abc',
             param2 = 'def'
       }

        // @ts-ignore placeholders is wrong when using multiple this needs to be a json string
        const result = await this.Influx.query(query, { placeholders: JSON.stringify(placeholder) }).catch((err: any) => {
        }
`
