### ISSUE TITLE
InfluxDB/Telegraf

### ISSUE THREAD

**Issue by danishv** [node-influx/node-influx#558]
## Expected Behavior

Array values to be written in influx with each line having timestamp

## Actual Behavior

I have perl script returning values in an array. I tried to write this in to influx, but am getting timestamp only for last line.

## Steps/Code to Reproduce the Problem

#use strict;
#use Shell qw(lynx);

my @myarr1=qx(snmpwalk -v2c -c 'test' 10.25.31.101 1.3.6.1.2.1.71.1.3.3.1.4);

#$myarr1=@myarr1;
#print "$myarr\n";

my @lines = @myarr1;

foreach (my $i=0; $i <= $#lines; $i++) {
#foreach (my $i=0; $i <= 0; $i++) {

                my @ip1 = split / /, $lines[$i];
                my @ip11 = chomp($ip1[6]);
                my $tunip = hex($ip1[3]).".".hex($ip1[4]).".".hex($ip1[5]).".".hex($ip1[6]);
                printf "dmvpn,host_name=GSM,Tunnel_IP=$tunip";
                printf "\n";
};

Output of telegraf test :
![image](https://user-images.githubusercontent.com/58603597/109132844-5700bb00-7765-11eb-82e9-0bb01048fa1d.png)

1. 1. 1.

```
const influx = require('influx')

// ...
```

## Specifications

- Version: telegraf 1.15.3
- Platform: influx,telegraf
- Subsystem:

**Comment by bencevans** [comment]
I'm afraid this is the wrong place for your query. This tracker is for issues with the community node-influx project (Node.js client for InfluxDB).

I'd suggest sending your query to the InfluxDB or Telegraf forums or the likes of StackOverflow.
