### ISSUE TITLE
Expose a "point validation" function

### ISSUE THREAD

**Issue by ugam44** [node-influx/node-influx#560]
It would be great if there was a function exposed that handled the logic of determining whether a point being passed to `influx.writePoints()` is valid or not. This is a non-issue when writing a single point, but if you are writing points in a batch, if a single point is malformed, the entire operation is aborted with no details provided about which point was problematic. I would like to have the option to manually pre-process all of the points to ensure that each point I am writing is valid according to the schema, so I can flag/handle or throw out the problematic points and let the rest of the batch operation proceed.

Currently, the logic for validating a point is embedded in the `influx.writePoints` function. I am proposing to extract that logic out to a separate function on the influx instance so it will be used by `influx.writePoints`, but is also accessible externally, like so:

```
writePoints(points, options = {}) {
  ...
  points.forEach((point) => {
    // const { fields = {}, tags = {}, measurement, timestamp } = point;
    // const schema = this._schema[database] && this._schema[database][measurement];
    // const fieldsPairs = schema
    //     ? schema.coerceFields(fields)
    //     : schema_1.coerceBadly(fields);
    // const tagsNames = schema ? schema.checkTags(tags) : Object.keys(tags);

    const { measurement, tags, fieldsPairs, tagsNames, castedTimestamp } = this.parsePoint(point, { database, precision });
   ...
});

parsePoint(point, options = {}) {
    const { database = this._defaultDB(), precision = "n" } = options;
    const { fields = {}, tags = {}, measurement, timestamp } = point;
    const schema = this._schema[database] && this._schema[database][measurement];
    const fieldsPairs = schema
        ? schema.coerceFields(fields)
        : schema_1.coerceBadly(fields);
    const tagsNames = schema ? schema.checkTags(tags) : Object.keys(tags);
    const castedTimestamp = timestamp && grammar.castTimestamp(timestamp, precision);
    return {
        fields,
        tags,
        measurement,
        timestamp,
        fieldsPairs,
        tagsNames,
        castedTimestamp
    }
}
```

This would allow for checking of the data point externally, like so:

```
points = points.filter(point => {
    try {
      let parsed = influx.parsePoint(point);
      return true;
    } catch(e) {
      logger.error(e);
      return false;
    }
});
// only points that have passed all schema and coercion checks will be written
influx.writePoints(points);
```

**Comment by bencevans** [comment]
Sounds good. I'm reluctant to change the functionality of failing when writing when there's single points that cause the error but extracting the functionality to manually validate and handle would be great. PR very welcome.

**Comment by ugam44** [comment]
@bencevans I completely agree that the current functionality of failing when writing when there's single points that cause an error is a good thing to have by default, and changing that would likely be a major breaking change. I have created a PR that extracts the validation logic into a separate function that is exposed to the user so they can manually handle any errors how it best suits them.
