### ISSUE TITLE
Reverse-Proxy Path Prefix

### ISSUE THREAD

**Issue by ccoenen** [node-influx/node-influx#57]
I keep my influxdb in a reverse-proxy'd subdirectory of my domain. This way, i can use its SSL Certificate without the need of one more certificate.

For this reason, my API does not look like this:

```
http://host/db/<dbname>...
```

but like this:

```
http://host/influx/db/<dbname>...
               ^-- this part is additional
```

Right now, i think, this is not supported. At least, i can't see, how.

**Comment by ericvrp** [comment]
I use another workaround for writePoints to a host with a pathPrefix by MonkeyPatching like this:

```
const influx = new Influx.InfluxDB({protocol: ts.protocol, host: ts.host, port: ts.port, username: ts.username, password: ts.password, database: ts.database})
if (ts.pathPrefix) {
  const orgPoolDiscard = influx.pool.discard
  influx.pool.discard = function(props) {
    props.path = ts.pathPrefix + props.path
    // console.log(props)
    return orgPoolDiscard.apply(this, arguments)
  }
}
```
