### ISSUE TITLE
Batch write multiple points

### ISSUE THREAD

**Issue by emilv** [node-influx/node-influx#6]
Influx supports writing multiple points at once and we would probably get much better performance with such batching.

I think the easiest is to rewrite `writePoint` so that it can take an array of points. The code should not be much different.

**Comment by elhenro** [comment]
does writeSeries exist in 5.2.0 (influx 1.7.6) ?

**Comment by bencevans** [comment]
You can provide an array of points to .writePoints... https://node-influx.github.io/class/src/index.js~InfluxDB.html#instance-method-writePoints

**Comment by elhenro** [comment]
Thanks @bencevans , but this always throws the Type error  `points.forEach is not a function,  at InfluxDB.writePoints`.

**Comment by bencevans** [comment]
Please could open a new issue and provide a code sample? Our tests covering
writePoints are all passing but maybe you've come across an edge case.

**Comment by elhenro** [comment]
@bencevans thank you for the support, but now it works as expected.
The error message `*.forEach is not a function` was just a little confusing to me, i did not pass the data in the right format.

After adjusting the points data to objects inside an array (not nested arrays) and adjusting the schema for it, it batch writes to influxdb. As expected this is a lot faster.
