### ISSUE TITLE
Issue with influx db login

### ISSUE THREAD

**Issue by developertom01** [node-influx/node-influx#638]
## Expected Behavior
I want to authenticate into influx db with node-influx

## Actual Behavior
I am able to log into the dashboard with the credentials that I added to the docker environment but I cannot use the same to authenticate with the APIendpoint or with node-influx

## Steps/Code to Reproduce the Problem

1. 1. 1.

```
        }
        this._instance = new InfluxDB({
            host: process.env.INFLUX_HOST,
            password: process.env.INFLUX_PASSWORD,
            username: process.env.INFLUX_USERNAME,
            schema: this.schemas,
            database: process.env.INFLUX_DB_NAME,
            port: parseInt(process.env.INFLUX_PORT!),
        });
        const dbNames = await this._instance.getDatabaseNames();
        console.log('DbNames', dbNames);

        if (!dbNames.includes(process.env.INFLUX_DB_NAME!)) {
            await this._instance.createDatabase(process.env.INFLUX_DB_NAME!);
        }
    }

```
```
        environment:
            - DOCKER_INFLUXDB_INIT_USERNAME=
            - DOCKER_INFLUXDB_INIT_PASSWORD=
            - DOCKER_INFLUXDB_INIT_BUCKET
            - DOCKER_INFLUXDB_INIT_ORG=
            - DOCKER_INFLUXDB_INIT_MODE=
            - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=
```

```
A 401 Unauthorized error occurred: {"code":"unauthorized","message":"Unauthorized"}
```

Can I get help on what credentials to use to log in?

**Comment by developertom01** [comment]
Actually 
Those environment variables are for the influx db service.

I did some few checks myself and I realized that the same code works for influx db 1.x but not 2.x or the latest tag

**Comment by bencevans** [comment]
Ah. I'm afraid we're not supporting InfluxDB v2, Influx now have their official client available at https://github.com/influxdata/influxdb-client-js
