### ISSUE TITLE
Support write-consistency levels

### ISSUE THREAD

**Issue by otoolep** [node-influx/node-influx#74]
Does this client code allow the user to select the write-consistency level?

https://github.com/influxdb/influxdb/blob/05d660a24de615ab2241063a70d418676ca6619b/cluster/points_writer.go#L25

Some people will want consistency other the default of ONE.

**Comment by nichdiekuh** [comment]
Is this a documented feature? I'll integrate anything that's available via influxdb API, as long as it's documented. Haven't found anything related to write consistency yet.

**Comment by otoolep** [comment]
Not quite documented yet, but the URL parameter is `consistency`.

**Comment by otoolep** [comment]
If this parameter is set to one of the strings here:

https://github.com/influxdb/influxdb/blob/05d660a24de615ab2241063a70d418676ca6619b/services/httpd/handler.go#L458

it sets the write consistency level to a level other than "one".

**Comment by nichdiekuh** [comment]
Ok, then the write consistency can be set via options:

```js
client.writePoint(seriesName,value, tags, {consistency : 'all'},callback);
```
Which leads me to answer your question with: Yes, it's possible with this client! ;)
