### ISSUE TITLE
Writing strings or JSON Objects with the v0.9 client

### ISSUE THREAD

**Issue by mrenz** [node-influx/node-influx#78]
Hi,

I did some testing with the new client and it appears that the writing of strings and JSON objects is pretty unintuitive. If I want to write a string, right now I have to write it as follows:
client.writePoint('seriesName', {value: ' "myString" '}, 'tagName: tag', cb);

If I want to write a JSON object, e.g.:
var myObject = {value: 'myString', key: 'value', key2: 'value2'};
client.writePoint('seriesName', myObject, 'tagName: tag', cb);
In this case I would have to manually add the " " to all of my strings inside the object. Now I would say that our client needs to add these " " automatically in case a value inside the second parameter is a string.

I think most users want to write a string as follows:
client.writePoint('seriesName', {value: 'myString'}, 'tagName: tag', cb);

I wanted to hear what you think about this, if you agree with me then I'll make a pull request. I was already able to fix this issue locally.

**Comment by nichdiekuh** [comment]
Hi Manuel,

the InfluxDB docs don't say anything about how to submit strings, but if masking them with quotes works, I'll gladly accept a PR. It would nice, if you could add a test-case for writing strings.

**Comment by mbejda** [comment]
:+1: 
I had a similar problem. Influxdb db does cast types it only enforces cast types. 
<pre>
curl -d "hamster runs=fast" "http://localhost:8086/write?u=root&p&database=test4&precision=ms&db=test4"
</pre>
will result to false while the following
<pre>
curl -d 'hamster runs="fast"' "http://localhost:8086/write?u=root&p&database=test4&precision=ms&db=test4"
</pre>
will result to hmaster runs="fast" in the database.

**Comment by nichdiekuh** [comment]
I've merged the PR from @mrenz. I'm going to release 4.0.1 soon
