### ISSUE TITLE
unable to parse : invalid boolean

### ISSUE THREAD

**Issue by yujinlim** [node-influx/node-influx#84]
Hi,

During `client.writePoint`, field parameters did not insert double quotes surrounding `string` value, therefore, it was trying to parse the value as `boolean`.

eg:

```js
/*
it will try to parse it as `activity, user=5 action=running`, which on InfluxDB version 0.9.1, will try to parse running value as boolean
*/
client.writePoint('activity', { action: 'running' }, {  user: 5 }, function(err, response){
 // handle response
});
```

is this expected behaviour? if no, i can submit a pull request. 

Thanks

**Comment by nichdiekuh** [comment]
I believe this has been fixed in #81 . I'm going to release an updated version later today.

**Comment by yujinlim** [comment]
:+1:

**Comment by nichdiekuh** [comment]
4.0.1 has just been released. If you still experience issues, please reopen this issue.
