### ISSUE TITLE
getMeasurements Values from the array

### ISSUE THREAD

**Issue by kgrvamsi** [node-influx/node-influx#90]
Hello,

Was trying to fetch the values from the getMeasurements Function but i see undefined when i try retrieving them

    client.getMeasurements(function(err,arrayMeasurements){
                console.log(arrayMeasurements[0].series)
                console.log(arrayMeasurements[0].series.values)
                console.log(arrayMeasurements[0].series.values.length)

                } )

Output 

    debug: [ { name: 'measurements',
    columns: [ 'name' ],
    values: [ [Object] ] } ]
    debug: [Functions:values]
    debug: 0

Db Values

    name: server_info
    tags: hostname=ip-10-20-30-00.ec2.internal, metric=memory, serverip=xx.xx.xx.xx
    time                            value
    ----                            -----
    2015-07-29T10:26:22.225Z        2101297152
    2015-07-29T10:36:00.502Z        2101297152

**Comment by MusicalCreeper01** [comment]
I had the same issue yesterday, to retrieve the values you need to do:
```
arrayMeasurements[0].series[0].values
```
I've opened an issue to ask if it can be changed, or a function added to just return an array of measurement names node-influx/node-influx#166

**Comment by connor4312** [comment]
Resolved with https://github.com/node-influx/node-influx/issues/166#issuecomment-252157950
