### ISSUE TITLE
Line protocol

### ISSUE THREAD

**Issue by ehacke** [node-influx/node-influx#93]
Should really use the line protocol for the newer versions of influx.
https://github.com/influxdb/influxdb/issues/3607

I'm trying to send huge amounts of data very frequently using this library and it just seems to choke no matter how I batch it.

It works fine at lower levels of use, but as soon as I deploy it to production it chokes.

**Comment by nichdiekuh** [comment]
We are already using the line protocol for writes. Where exactly does it "choke"?

**Comment by ehacke** [comment]
Oh ok, sorry about that. I looked at the code quickly, but I must have missed that. Incorrectly assumed that was my problem based on the issue I referenced.

It's odd. When I run it in the development environment it works fine. I have writes being done as batches every 1-2 seconds. But when deployed to production, it seems to be able to write at first, then quickly fails back to throwing errors saying: [Error: No host available]. I can't easily tell what proportion of the writes are getting through right now.

For reference, I'm constantly writing 200-400 points per second, in single batches every second. Which doesn't seem as large as I thought.

Querying the production DB via http, I can see that the database and series exist. Querying the data basically hangs the request. Some very limited queries do eventually return, but it takes ~2 minutes to get a response. Aggregated queries over a 10 minute data set don't seem to return at all, maybe just really long.

The only reason I suspected the library was because of the issue I referenced. But it seems like it's probably an influx issue, or the way I'm writing the data.

**Comment by nichdiekuh** [comment]
Hm, it sounds like an issue with InfluxDB for me.

When a request runs into a timeout or receives and http error, node-influx removes the server from the list of available servers and tries the next one (if configured).
You say that even querying the data stalls the DB, hence I suggest to open an issue @ InfluxDB. However, if there's anything that might be related to this driver, please reopen this ticket and we'll have a closer look :)

**Comment by ehacke** [comment]
@nichdiekuh thanks very much, sorry for jumping to conclusions there.
