### ISSUE TITLE
Spaces or commas in the key are not escaped

### ISSUE THREAD

**Issue by janantala** [node-influx/node-influx#96]
According to https://github.com/influxdb/influxdb/blob/master/tsdb/README.md#key tag values must escape any spaces or commas using a backslash.

However they are not in the `_createKeyTagString` method

**Comment by dandv** [comment]
It's not [just tag values](https://docs.influxdata.com/influxdb/latest/write_protocols/line_protocol_tutorial/#special-characters):

> For tag keys, tag values, and field keys always use a backslash character \ to escape: commas, equal signs, spaces

[We don't do all of that.](https://github.com/node-influx/node-influx/blob/master/index.js#L302)

Happy to send a PR, but please merge my other PRs first.

**Comment by b4dboi** [comment]
Hi, I think this issue should be reopened. I use node-red-contrib-influxdb in NodeRed, that use the node-influx library by calling writePoints method. Unfortunately some of my tag values contain backslashes, and I found that all backslashes are doubled regardless of its origin (tag keys, tag values, field keys) making the data written to the InfluxDB confusing. As stated in https://docs.influxdata.com/influxdb/v1.7/write_protocols/line_protocol_reference/, only backslashes contained in string field values must be escaped. However, the grammar.escape.tag method escapes the backslash char as well, which is needless and complies with the citation by @dandv.
> For tag keys, tag values, and field keys always use a backslash character \ to escape: **commas, equal signs, spaces**

**Comment by bencevans** [comment]
PR would be much appreciated :+1:

**Comment by b4dboi** [comment]
I would like to, but I am not a Node.js developer, and it would be hard for me to set up the whole environment for the project. I was able to reproduce the code piece by piece and I think the problem is at following line, where is harcoded the string `\\\\` in the RegExp. https://github.com/node-influx/node-influx/blob/48b5fc79655c058a5c919ed5da8bbde9444c5411/src/grammar/escape.ts#L41

**Comment by bencevans** [comment]
Fix provided in #401. Released to npm in `v5.1.1`.
